// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum C4LightEffect_t : uint
{
 eLightEffectNone = 0,

 eLightEffectDropped = 1,

 eLightEffectThirdPersonHeld = 2,
}