// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum CNmFloatMathNode__Operator_t : byte
{
 Add = 0,

 Sub = 1,

 Mul = 2,

 Div = 3,

 Mod = 4,

 Abs = 5,

 Negate = 6,

 Floor = 7,

 Ceiling = 8,

 IntegerPart = 9,

 FractionalPart = 10,

 InverseFractionalPart = 11,
}