// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum HierarchyType_t : uint
{
 HIERARCHY_NONE = 0,

 HIERARCHY_BONE_MERGE = 1,

 HIERARCHY_ATTACHMENT = 2,

 HIERARCHY_ABSORIGIN = 3,

 HIERARCHY_BONE = 4,

 HIERARCHY_TYPE_COUNT = 5,
}