// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum ParticleVRHandChoiceList_t : uint
{
 PARTICLE_VRHAND_LEFT = 0,

 PARTICLE_VRHAND_RIGHT = 1,

 PARTICLE_VRHAND_CP = 2,

 PARTICLE_VRHAND_CP_OBJECT = 3,
}