// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum PFNoiseTurbulence_t : uint
{
 PF_NOISE_TURB_NONE = 0,

 PF_NOISE_TURB_HIGHLIGHT = 1,

 PF_NOISE_TURB_FEEDBACK = 2,

 PF_NOISE_TURB_LOOPY = 3,

 PF_NOISE_TURB_CONTRAST = 4,

 PF_NOISE_TURB_ALTERNATE = 5,
}