// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum SeqPoseSetting_t : uint
{
 SEQ_POSE_SETTING_CONSTANT = 0,

 SEQ_POSE_SETTING_ROTATION = 1,

 SEQ_POSE_SETTING_POSITION = 2,

 SEQ_POSE_SETTING_VELOCITY = 3,
}