// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum WeaponAttackType_t : uint
{
 eInvalid = uint.MaxValue,

 ePrimary = 0,

 eSecondary = 1,

 eCount = 2,
}