// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AggregateLODSetup_t : ISchemaClass<AggregateLODSetup_t>
{
    static AggregateLODSetup_t ISchemaClass<AggregateLODSetup_t>.From(nint handle) => new AggregateLODSetup_tImpl(handle);
    static int ISchemaClass<AggregateLODSetup_t>.Size => 40;
    static string? ISchemaClass<AggregateLODSetup_t>.ClassName => null;


    public ref Vector LODOrigin { get; }

    public ref float MaxObjectScale { get; }

    public ref CUtlVector<float> SwitchDistances { get; }


}