// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AttachmentHandle_t : ISchemaClass<AttachmentHandle_t>
{
    static AttachmentHandle_t ISchemaClass<AttachmentHandle_t>.From(nint handle) => new AttachmentHandle_tImpl(handle);
    static int ISchemaClass<AttachmentHandle_t>.Size => 1;
    static string? ISchemaClass<AttachmentHandle_t>.ClassName => null;


    public ref byte Value { get; }


}