// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_CreateWithinCapsuleTransform : CParticleFunctionInitializer, ISchemaClass<C_INIT_CreateWithinCapsuleTransform>
{
    static C_INIT_CreateWithinCapsuleTransform ISchemaClass<C_INIT_CreateWithinCapsuleTransform>.From(nint handle) => new C_INIT_CreateWithinCapsuleTransformImpl(handle);
    static int ISchemaClass<C_INIT_CreateWithinCapsuleTransform>.Size => 5872;
    static string? ISchemaClass<C_INIT_CreateWithinCapsuleTransform>.ClassName => null;


    public CPerParticleFloatInput RadiusMin { get; }

    public CPerParticleFloatInput RadiusMax { get; }

    public CPerParticleFloatInput Height { get; }

    public CParticleTransformInput TransformInput { get; }

    public CPerParticleFloatInput SpeedMin { get; }

    public CPerParticleFloatInput SpeedMax { get; }

    public ref float SpeedRandExp { get; }

    public CPerParticleVecInput LocalCoordinateSystemSpeedMin { get; }

    public CPerParticleVecInput LocalCoordinateSystemSpeedMax { get; }

    public ParticleAttributeIndex_t FieldOutput { get; }

    public ParticleAttributeIndex_t FieldVelocity { get; }


}