// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_INIT_SequenceLifeTime : CParticleFunctionInitializer, ISchemaClass<C_INIT_SequenceLifeTime>
{
    static C_INIT_SequenceLifeTime ISchemaClass<C_INIT_SequenceLifeTime>.From(nint handle) => new C_INIT_SequenceLifeTimeImpl(handle);
    static int ISchemaClass<C_INIT_SequenceLifeTime>.Size => 480;
    static string? ISchemaClass<C_INIT_SequenceLifeTime>.ClassName => null;


    public ref float Framerate { get; }


}