// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_ForceControlPointStub : CParticleFunctionPreEmission, ISchemaClass<C_OP_ForceControlPointStub>
{
    static C_OP_ForceControlPointStub ISchemaClass<C_OP_ForceControlPointStub>.From(nint handle) => new C_OP_ForceControlPointStubImpl(handle);
    static int ISchemaClass<C_OP_ForceControlPointStub>.Size => 480;
    static string? ISchemaClass<C_OP_ForceControlPointStub>.ClassName => null;


    public ref int ControlPoint { get; }


}