// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_OP_SetCPtoVector : CParticleFunctionOperator, ISchemaClass<C_OP_SetCPtoVector>
{
    static C_OP_SetCPtoVector ISchemaClass<C_OP_SetCPtoVector>.From(nint handle) => new C_OP_SetCPtoVectorImpl(handle);
    static int ISchemaClass<C_OP_SetCPtoVector>.Size => 472;
    static string? ISchemaClass<C_OP_SetCPtoVector>.ClassName => null;


    public ref int CPInput { get; }

    public ParticleAttributeIndex_t FieldOutput { get; }


}