// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphControllerBase : ISchemaClass<CAnimGraphControllerBase>
{
    static CAnimGraphControllerBase ISchemaClass<CAnimGraphControllerBase>.From(nint handle) => new CAnimGraphControllerBaseImpl(handle);
    static int ISchemaClass<CAnimGraphControllerBase>.Size => 128;
    static string? ISchemaClass<CAnimGraphControllerBase>.ClassName => null;


    // CUtlVectorFixedGrowable< CGlobalSymbol, 8 >
    public SchemaUntypedField ParamsToResetInPostGraphUpdate { get; }


}