// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimUpdateSharedData : ISchemaClass<CAnimUpdateSharedData>
{
    static CAnimUpdateSharedData ISchemaClass<CAnimUpdateSharedData>.From(nint handle) => new CAnimUpdateSharedDataImpl(handle);
    static int ISchemaClass<CAnimUpdateSharedData>.Size => 256;
    static string? ISchemaClass<CAnimUpdateSharedData>.ClassName => null;


    public ref CUtlVector<SchemaUntypedField> Nodes { get; }

    // CUtlHashtable< CAnimNodePath, int32 >
    public SchemaUntypedField NodeIndexMap { get; }

    public ref CUtlVector<SchemaUntypedField> Components { get; }

    // CSmartPtr< CAnimParameterManagerUpdater >
    public SchemaUntypedField ParamListUpdater { get; }

    // CSmartPtr< CAnimTagManagerUpdater >
    public SchemaUntypedField TagManagerUpdater { get; }

    // CSmartPtr< CAnimScriptManager >
    public SchemaUntypedField ScriptManager { get; }

    public CAnimGraphSettingsManager Settings { get; }

    // CSmartPtr< CStaticPoseCacheBuilder >
    public SchemaUntypedField StaticPoseCache { get; }

    // CSmartPtr< CAnimSkeleton >
    public SchemaUntypedField Skeleton { get; }

    public CAnimNodePath RootNodePath { get; }


}