// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CDspPresetModifierList : ISchemaClass<CDspPresetModifierList>
{
    static CDspPresetModifierList ISchemaClass<CDspPresetModifierList>.From(nint handle) => new CDspPresetModifierListImpl(handle);
    static int ISchemaClass<CDspPresetModifierList>.Size => 32;
    static string? ISchemaClass<CDspPresetModifierList>.ClassName => null;


    public string DspName { get; set; }

    public ref CUtlVector<CDSPMixgroupModifier> Modifiers { get; }


}