// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CEnvMuzzleFlash : CPointEntity, ISchemaClass<CEnvMuzzleFlash>
{
    static CEnvMuzzleFlash ISchemaClass<CEnvMuzzleFlash>.From(nint handle) => new CEnvMuzzleFlashImpl(handle);
    static int ISchemaClass<CEnvMuzzleFlash>.Size => 1280;
    static string? ISchemaClass<CEnvMuzzleFlash>.ClassName => "env_muzzleflash";


    public ref float Scale { get; }

    public string ParentAttachment { get; set; }


}