// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFuncTrackAuto : CFuncTrackChange, ISchemaClass<CFuncTrackAuto>
{
    static CFuncTrackAuto ISchemaClass<CFuncTrackAuto>.From(nint handle) => new CFuncTrackAutoImpl(handle);
    static int ISchemaClass<CFuncTrackAuto>.Size => 2272;
    static string? ISchemaClass<CFuncTrackAuto>.ClassName => "func_trackautochange";




}