// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFuncWater : CBaseModelEntity, ISchemaClass<CFuncWater>
{
    static CFuncWater ISchemaClass<CFuncWater>.From(nint handle) => new CFuncWaterImpl(handle);
    static int ISchemaClass<CFuncWater>.Size => 2288;
    static string? ISchemaClass<CFuncWater>.ClassName => "func_water";


    public CBuoyancyHelper BuoyancyHelper { get; }


}