// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CGameRules : ISchemaClass<CGameRules>
{
    static CGameRules ISchemaClass<CGameRules>.From(nint handle) => new CGameRulesImpl(handle);
    static int ISchemaClass<CGameRules>.Size => 192;
    static string? ISchemaClass<CGameRules>.ClassName => null;


    public ref CNetworkVarChainer __m_pChainEntity { get; }

    public string QuestName { get; set; }

    public ref int QuestPhase { get; }

    public ref int TotalPausedTicks { get; }

    public ref int PauseStartTick { get; }

    public ref bool GamePaused { get; }

    public void TotalPausedTicksUpdated();
    public void PauseStartTickUpdated();
    public void GamePausedUpdated();
}