// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CInfoPlayerCounterterrorist : SpawnPoint, ISchemaClass<CInfoPlayerCounterterrorist>
{
    static CInfoPlayerCounterterrorist ISchemaClass<CInfoPlayerCounterterrorist>.From(nint handle) => new CInfoPlayerCounterterroristImpl(handle);
    static int ISchemaClass<CInfoPlayerCounterterrorist>.Size => 1280;
    static string? ISchemaClass<CInfoPlayerCounterterrorist>.ClassName => "info_player_counterterrorist";




}