// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CInfoInstructorHintBombTargetB : CPointEntity, ISchemaClass<CInfoInstructorHintBombTargetB>
{
    static CInfoInstructorHintBombTargetB ISchemaClass<CInfoInstructorHintBombTargetB>.From(nint handle) => new CInfoInstructorHintBombTargetBImpl(handle);
    static int ISchemaClass<CInfoInstructorHintBombTargetB>.Size => 1264;
    static string? ISchemaClass<CInfoInstructorHintBombTargetB>.ClassName => "info_bomb_target_hint_B";




}