// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CInfoTargetServerOnly : CServerOnlyPointEntity, ISchemaClass<CInfoTargetServerOnly>
{
    static CInfoTargetServerOnly ISchemaClass<CInfoTargetServerOnly>.From(nint handle) => new CInfoTargetServerOnlyImpl(handle);
    static int ISchemaClass<CInfoTargetServerOnly>.Size => 1264;
    static string? ISchemaClass<CInfoTargetServerOnly>.ClassName => "info_target_server_only";




}