// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmCachedPoseWriteTask : CNmPoseTask, ISchemaClass<CNmCachedPoseWriteTask>
{
    static CNmCachedPoseWriteTask ISchemaClass<CNmCachedPoseWriteTask>.From(nint handle) => new CNmCachedPoseWriteTaskImpl(handle);
    static int ISchemaClass<CNmCachedPoseWriteTask>.Size => 96;
    static string? ISchemaClass<CNmCachedPoseWriteTask>.ClassName => null;




}