// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmChainLookatTask : CNmPoseTask, ISchemaClass<CNmChainLookatTask>
{
    static CNmChainLookatTask ISchemaClass<CNmChainLookatTask>.From(nint handle) => new CNmChainLookatTaskImpl(handle);
    static int ISchemaClass<CNmChainLookatTask>.Size => 144;
    static string? ISchemaClass<CNmChainLookatTask>.ClassName => null;


    public ref int ChainEndBoneIdx { get; }

    public ref int NumBonesInChain { get; }

    public ref Vector ChainForwardDir { get; }

    public ref float BlendWeight { get; }

    public ref float HorizontalAngleLimitDegrees { get; }

    public ref float VerticalAngleLimitDegrees { get; }

    public ref Vector LookatTarget { get; }

    public ref bool IsTargetInWorldSpace { get; }

    public ref bool IsRunningFromDeserializedData { get; }

    public ref float HorizontalAngleDegrees { get; }

    public ref float VerticalAngleDegrees { get; }


}