// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmIDEventNode__CDefinition : CNmIDValueNode__CDefinition, ISchemaClass<CNmIDEventNode__CDefinition>
{
    static CNmIDEventNode__CDefinition ISchemaClass<CNmIDEventNode__CDefinition>.From(nint handle) => new CNmIDEventNode__CDefinitionImpl(handle);
    static int ISchemaClass<CNmIDEventNode__CDefinition>.Size => 32;
    static string? ISchemaClass<CNmIDEventNode__CDefinition>.ClassName => null;


    public ref short SourceStateNodeIdx { get; }

    public CNmBitFlags EventConditionRules { get; }

    public ref CGlobalSymbol DefaultValue { get; }


}