// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CParticleFunctionEmitter : CParticleFunction, ISchemaClass<CParticleFunctionEmitter>
{
    static CParticleFunctionEmitter ISchemaClass<CParticleFunctionEmitter>.From(nint handle) => new CParticleFunctionEmitterImpl(handle);
    static int ISchemaClass<CParticleFunctionEmitter>.Size => 472;
    static string? ISchemaClass<CParticleFunctionEmitter>.ClassName => null;


    public ref int EmitterIndex { get; }


}