// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CParamSpanUpdater : ISchemaClass<CParamSpanUpdater>
{
    static CParamSpanUpdater ISchemaClass<CParamSpanUpdater>.From(nint handle) => new CParamSpanUpdaterImpl(handle);
    static int ISchemaClass<CParamSpanUpdater>.Size => 24;
    static string? ISchemaClass<CParamSpanUpdater>.ClassName => null;


    public ref CUtlVector<ParamSpan_t> Spans { get; }


}