// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPathCornerCrash : CPathCorner, ISchemaClass<CPathCornerCrash>
{
    static CPathCornerCrash ISchemaClass<CPathCornerCrash>.From(nint handle) => new CPathCornerCrashImpl(handle);
    static int ISchemaClass<CPathCornerCrash>.Size => 1312;
    static string? ISchemaClass<CPathCornerCrash>.ClassName => "path_corner_crash";




}