// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPhysExplosion : CPointEntity, ISchemaClass<CPhysExplosion>
{
    static CPhysExplosion ISchemaClass<CPhysExplosion>.From(nint handle) => new CPhysExplosionImpl(handle);
    static int ISchemaClass<CPhysExplosion>.Size => 1344;
    static string? ISchemaClass<CPhysExplosion>.ClassName => "env_physexplosion";


    public ref bool ExplodeOnSpawn { get; }

    public ref float Magnitude { get; }

    public ref float Damage { get; }

    public ref float Radius { get; }

    public string TargetEntityName { get; set; }

    public ref float InnerRadius { get; }

    public ref float PushScale { get; }

    public ref bool ConvertToDebrisWhenPossible { get; }

    public ref bool AffectInvulnerableEnts { get; }

    public ref CEntityIOOutput OnPushedPlayer { get; }


}