// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPhysThruster : CPhysForce, ISchemaClass<CPhysThruster>
{
    static CPhysThruster ISchemaClass<CPhysThruster>.From(nint handle) => new CPhysThrusterImpl(handle);
    static int ISchemaClass<CPhysThruster>.Size => 1376;
    static string? ISchemaClass<CPhysThruster>.ClassName => "phys_thruster";


    public ref Vector LocalOrigin { get; }


}