// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPhysicsPropOverride : CPhysicsProp, ISchemaClass<CPhysicsPropOverride>
{
    static CPhysicsPropOverride ISchemaClass<CPhysicsPropOverride>.From(nint handle) => new CPhysicsPropOverrideImpl(handle);
    static int ISchemaClass<CPhysicsPropOverride>.Size => 3584;
    static string? ISchemaClass<CPhysicsPropOverride>.ClassName => "prop_physics_override";




}