// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPlayer_ItemServices : CPlayerPawnComponent, ISchemaClass<CPlayer_ItemServices>
{
    static CPlayer_ItemServices ISchemaClass<CPlayer_ItemServices>.From(nint handle) => new CPlayer_ItemServicesImpl(handle);
    static int ISchemaClass<CPlayer_ItemServices>.Size => 64;
    static string? ISchemaClass<CPlayer_ItemServices>.ClassName => null;




}