// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPointProximitySensor : CPointEntity, ISchemaClass<CPointProximitySensor>
{
    static CPointProximitySensor ISchemaClass<CPointProximitySensor>.From(nint handle) => new CPointProximitySensorImpl(handle);
    static int ISchemaClass<CPointProximitySensor>.Size => 1312;
    static string? ISchemaClass<CPointProximitySensor>.ClassName => "point_proximity_sensor";


    public ref bool Disabled { get; }

    public ref CHandle<CBaseEntity> TargetEntity { get; }

    // CEntityOutputTemplate< float32 >
    public SchemaUntypedField Distance { get; }


}