// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSosGroupActionTimeLimitSchema : CSosGroupActionSchema, ISchemaClass<CSosGroupActionTimeLimitSchema>
{
    static CSosGroupActionTimeLimitSchema ISchemaClass<CSosGroupActionTimeLimitSchema>.From(nint handle) => new CSosGroupActionTimeLimitSchemaImpl(handle);
    static int ISchemaClass<CSosGroupActionTimeLimitSchema>.Size => 16;
    static string? ISchemaClass<CSosGroupActionTimeLimitSchema>.ClassName => null;


    public ref float MaxDuration { get; }


}