// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSoundEventSphereEntity : CSoundEventEntity, ISchemaClass<CSoundEventSphereEntity>
{
    static CSoundEventSphereEntity ISchemaClass<CSoundEventSphereEntity>.From(nint handle) => new CSoundEventSphereEntityImpl(handle);
    static int ISchemaClass<CSoundEventSphereEntity>.Size => 1472;
    static string? ISchemaClass<CSoundEventSphereEntity>.ClassName => "snd_event_sphere";


    public ref float Radius { get; }

    public void RadiusUpdated();
}