// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSoundEnvelope : ISchemaClass<CSoundEnvelope>
{
    static CSoundEnvelope ISchemaClass<CSoundEnvelope>.From(nint handle) => new CSoundEnvelopeImpl(handle);
    static int ISchemaClass<CSoundEnvelope>.Size => 16;
    static string? ISchemaClass<CSoundEnvelope>.ClassName => null;


    public ref float Current { get; }

    public ref float Target { get; }

    public ref float Rate { get; }

    public ref bool Forceupdate { get; }


}