// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestEffect : CBaseEntity, ISchemaClass<CTestEffect>
{
    static CTestEffect ISchemaClass<CTestEffect>.From(nint handle) => new CTestEffectImpl(handle);
    static int ISchemaClass<CTestEffect>.Size => 1568;
    static string? ISchemaClass<CTestEffect>.ClassName => "test_effect";


    public ref int Loop { get; }

    public ref int Beam { get; }

    public ISchemaClassFixedArray<CBeam> Beam1 { get; }

    public ISchemaClassFixedArray<GameTime_t> BeamTime { get; }

    public GameTime_t StartTime { get; }


}