// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTextureBasedAnimatable : CBaseModelEntity, ISchemaClass<CTextureBasedAnimatable>
{
    static CTextureBasedAnimatable ISchemaClass<CTextureBasedAnimatable>.From(nint handle) => new CTextureBasedAnimatableImpl(handle);
    static int ISchemaClass<CTextureBasedAnimatable>.Size => 2064;
    static string? ISchemaClass<CTextureBasedAnimatable>.ClassName => "hl_vr_texture_based_animatable";


    public ref bool Loop { get; }

    public ref float FPS { get; }

    public ref CStrongHandle<InfoForResourceTypeCTextureBase> PositionKeys { get; }

    public ref CStrongHandle<InfoForResourceTypeCTextureBase> RotationKeys { get; }

    public ref Vector AnimationBoundsMin { get; }

    public ref Vector AnimationBoundsMax { get; }

    public ref float StartTime { get; }

    public ref float StartFrame { get; }

    public void LoopUpdated();
    public void FPSUpdated();
    public void PositionKeysUpdated();
    public void RotationKeysUpdated();
    public void AnimationBoundsMinUpdated();
    public void AnimationBoundsMaxUpdated();
    public void StartTimeUpdated();
    public void StartFrameUpdated();
}