// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTriggerVolume : CBaseModelEntity, ISchemaClass<CTriggerVolume>
{
    static CTriggerVolume ISchemaClass<CTriggerVolume>.From(nint handle) => new CTriggerVolumeImpl(handle);
    static int ISchemaClass<CTriggerVolume>.Size => 2024;
    static string? ISchemaClass<CTriggerVolume>.ClassName => "trigger_transition";


    public string FilterName { get; set; }

    public ref CHandle<CBaseFilter> Filter { get; }


}