// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVoiceContainerBlender : CVoiceContainerBase, ISchemaClass<CVoiceContainerBlender>
{
    static CVoiceContainerBlender ISchemaClass<CVoiceContainerBlender>.From(nint handle) => new CVoiceContainerBlenderImpl(handle);
    static int ISchemaClass<CVoiceContainerBlender>.Size => 240;
    static string? ISchemaClass<CVoiceContainerBlender>.ClassName => null;


    public CSoundContainerReference FirstSound { get; }

    public CSoundContainerReference SecondSound { get; }

    public ref float BlendFactor { get; }


}