// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVoiceContainerSet : CVoiceContainerBase, ISchemaClass<CVoiceContainerSet>
{
    static CVoiceContainerSet ISchemaClass<CVoiceContainerSet>.From(nint handle) => new CVoiceContainerSetImpl(handle);
    static int ISchemaClass<CVoiceContainerSet>.Size => 208;
    static string? ISchemaClass<CVoiceContainerSet>.ClassName => null;


    public ref CUtlVector<CVoiceContainerSetElement> SoundsToPlay { get; }


}