// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface EventModInitialized_t : ISchemaClass<EventModInitialized_t>
{
    static EventModInitialized_t ISchemaClass<EventModInitialized_t>.From(nint handle) => new EventModInitialized_tImpl(handle);
    static int ISchemaClass<EventModInitialized_t>.Size => 1;
    static string? ISchemaClass<EventModInitialized_t>.ClassName => null;




}