// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface EventClientPostOutput_t : ISchemaClass<EventClientPostOutput_t>
{
    static EventClientPostOutput_t ISchemaClass<EventClientPostOutput_t>.From(nint handle) => new EventClientPostOutput_tImpl(handle);
    static int ISchemaClass<EventClientPostOutput_t>.Size => 64;
    static string? ISchemaClass<EventClientPostOutput_t>.ClassName => null;


    public EngineLoopState_t LoopState { get; }

    public ref double RenderTime { get; }

    public ref float RenderFrameTime { get; }

    public ref float RenderFrameTimeUnbounded { get; }

    public ref bool RenderOnly { get; }


}