// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface IKSolverSettings_t : ISchemaClass<IKSolverSettings_t>
{
    static IKSolverSettings_t ISchemaClass<IKSolverSettings_t>.From(nint handle) => new IKSolverSettings_tImpl(handle);
    static int ISchemaClass<IKSolverSettings_t>.Size => 12;
    static string? ISchemaClass<IKSolverSettings_t>.ClassName => null;


    public ref IKSolverType SolverType { get; }

    public ref int NumIterations { get; }

    public ref EIKEndEffectorRotationFixUpMode EndEffectorRotationFixUpMode { get; }


}