// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface InfoForResourceTypeWorld_t : ISchemaClass<InfoForResourceTypeWorld_t>
{
    static InfoForResourceTypeWorld_t ISchemaClass<InfoForResourceTypeWorld_t>.From(nint handle) => new InfoForResourceTypeWorld_tImpl(handle);
    static int ISchemaClass<InfoForResourceTypeWorld_t>.Size => 1;
    static string? ISchemaClass<InfoForResourceTypeWorld_t>.ClassName => null;




}