// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface InfoForResourceTypeCDOTANovelsList : ISchemaClass<InfoForResourceTypeCDOTANovelsList>
{
    static InfoForResourceTypeCDOTANovelsList ISchemaClass<InfoForResourceTypeCDOTANovelsList>.From(nint handle) => new InfoForResourceTypeCDOTANovelsListImpl(handle);
    static int ISchemaClass<InfoForResourceTypeCDOTANovelsList>.Size => 1;
    static string? ISchemaClass<InfoForResourceTypeCDOTANovelsList>.ClassName => null;




}