// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface InfoForResourceTypeCJavaScriptResource : ISchemaClass<InfoForResourceTypeCJavaScriptResource>
{
    static InfoForResourceTypeCJavaScriptResource ISchemaClass<InfoForResourceTypeCJavaScriptResource>.From(nint handle) => new InfoForResourceTypeCJavaScriptResourceImpl(handle);
    static int ISchemaClass<InfoForResourceTypeCJavaScriptResource>.Size => 1;
    static string? ISchemaClass<InfoForResourceTypeCJavaScriptResource>.ClassName => null;




}