// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface MoodAnimation_t : ISchemaClass<MoodAnimation_t>
{
    static MoodAnimation_t ISchemaClass<MoodAnimation_t>.From(nint handle) => new MoodAnimation_tImpl(handle);
    static int ISchemaClass<MoodAnimation_t>.Size => 16;
    static string? ISchemaClass<MoodAnimation_t>.ClassName => null;


    // CModelAnimNameWithDeltas
    public SchemaUntypedField Name { get; }

    public ref float Weight { get; }


}