// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SceneEventId_t : ISchemaClass<SceneEventId_t>
{
    static SceneEventId_t ISchemaClass<SceneEventId_t>.From(nint handle) => new SceneEventId_tImpl(handle);
    static int ISchemaClass<SceneEventId_t>.Size => 4;
    static string? ISchemaClass<SceneEventId_t>.ClassName => null;


    public ref uint Value { get; }


}