// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SignatureOutflow_Continue : CPulse_OutflowConnection, ISchemaClass<SignatureOutflow_Continue>
{
    static SignatureOutflow_Continue ISchemaClass<SignatureOutflow_Continue>.From(nint handle) => new SignatureOutflow_ContinueImpl(handle);
    static int ISchemaClass<SignatureOutflow_Continue>.Size => 72;
    static string? ISchemaClass<SignatureOutflow_Continue>.ClassName => null;




}