// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AutoRoomDoorwayPairs_tImpl : SchemaClass, AutoRoomDoorwayPairs_t
{
    public AutoRoomDoorwayPairs_tImpl(nint handle) : base(handle) { }

    private static nint? _P1Offset;

    public ref Vector P1 {
        get {
            _P1Offset = _P1Offset ?? Schema.GetOffset(0x735A94BECD01805E);
            return ref _Handle.AsRef<Vector>(_P1Offset!.Value);
        }
    }
    private static nint? _P2Offset;

    public ref Vector P2 {
        get {
            _P2Offset = _P2Offset ?? Schema.GetOffset(0x735A94BECC017ECB);
            return ref _Handle.AsRef<Vector>(_P2Offset!.Value);
        }
    }


}