// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class BakedLightingInfo_t__BakedShadowAssignment_tImpl : SchemaClass, BakedLightingInfo_t__BakedShadowAssignment_t {

  public BakedLightingInfo_t__BakedShadowAssignment_tImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _LightHashOffset = new(() => Schema.GetOffset(0x1A17A94C74E0509B), LazyThreadSafetyMode.None);

  public ref uint LightHash {
    get => ref _Handle.AsRef<uint>(_LightHashOffset.Value);
  }
  private static readonly Lazy<nint> _MapHashOffset = new(() => Schema.GetOffset(0x1A17A94CD5C02B59), LazyThreadSafetyMode.None);

  public ref uint MapHash {
    get => ref _Handle.AsRef<uint>(_MapHashOffset.Value);
  }
  private static readonly Lazy<nint> _ShadowChannelOffset = new(() => Schema.GetOffset(0x1A17A94C10A02654), LazyThreadSafetyMode.None);

  public ref byte ShadowChannel {
    get => ref _Handle.AsRef<byte>(_ShadowChannelOffset.Value);
  }


}