// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_ColorLitPerParticleImpl : CParticleFunctionInitializerImpl, C_INIT_ColorLitPerParticle {

  public C_INIT_ColorLitPerParticleImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _ColorMinOffset = new(() => Schema.GetOffset(0xA196BF87552A5834), LazyThreadSafetyMode.None);

  public ref Color ColorMin {
    get => ref _Handle.AsRef<Color>(_ColorMinOffset.Value);
  }
  private static readonly Lazy<nint> _ColorMaxOffset = new(() => Schema.GetOffset(0xA196BF87433DC396), LazyThreadSafetyMode.None);

  public ref Color ColorMax {
    get => ref _Handle.AsRef<Color>(_ColorMaxOffset.Value);
  }
  private static readonly Lazy<nint> _TintMinOffset = new(() => Schema.GetOffset(0xA196BF8750B36A60), LazyThreadSafetyMode.None);

  public ref Color TintMin {
    get => ref _Handle.AsRef<Color>(_TintMinOffset.Value);
  }
  private static readonly Lazy<nint> _TintMaxOffset = new(() => Schema.GetOffset(0xA196BF8766A0054A), LazyThreadSafetyMode.None);

  public ref Color TintMax {
    get => ref _Handle.AsRef<Color>(_TintMaxOffset.Value);
  }
  private static readonly Lazy<nint> _TintPercOffset = new(() => Schema.GetOffset(0xA196BF87E32BE3C6), LazyThreadSafetyMode.None);

  public ref float TintPerc {
    get => ref _Handle.AsRef<float>(_TintPercOffset.Value);
  }
  private static readonly Lazy<nint> _TintBlendModeOffset = new(() => Schema.GetOffset(0xA196BF87B80E5314), LazyThreadSafetyMode.None);

  public ref ParticleColorBlendMode_t TintBlendMode {
    get => ref _Handle.AsRef<ParticleColorBlendMode_t>(_TintBlendModeOffset.Value);
  }
  private static readonly Lazy<nint> _LightAmplificationOffset = new(() => Schema.GetOffset(0xA196BF87C8D7C0AD), LazyThreadSafetyMode.None);

  public ref float LightAmplification {
    get => ref _Handle.AsRef<float>(_LightAmplificationOffset.Value);
  }


}