// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_PinParticleToCPImpl : CParticleFunctionOperatorImpl, C_OP_PinParticleToCP
{
    public C_OP_PinParticleToCPImpl(nint handle) : base(handle) { }

    private static nint? _ControlPointNumberOffset;

    public ref int ControlPointNumber {
        get {
            _ControlPointNumberOffset = _ControlPointNumberOffset ?? Schema.GetOffset(0xE4FC73983F31A6BD);
            return ref _Handle.AsRef<int>(_ControlPointNumberOffset!.Value);
        }
    }
    private static nint? _OffsetOffset;

    public CParticleCollectionVecInput Offset {
        get {
            _OffsetOffset = _OffsetOffset ?? Schema.GetOffset(0xE4FC7398BD25CC2A);
            return new CParticleCollectionVecInputImpl(_Handle + _OffsetOffset!.Value);
        }
    }
    private static nint? _OffsetLocalOffset;

    public ref bool OffsetLocal {
        get {
            _OffsetLocalOffset = _OffsetLocalOffset ?? Schema.GetOffset(0xE4FC7398F07D31C1);
            return ref _Handle.AsRef<bool>(_OffsetLocalOffset!.Value);
        }
    }
    private static nint? _ParticleSelectionOffset;

    public ref ParticleSelection_t ParticleSelection {
        get {
            _ParticleSelectionOffset = _ParticleSelectionOffset ?? Schema.GetOffset(0xE4FC7398A2307EA7);
            return ref _Handle.AsRef<ParticleSelection_t>(_ParticleSelectionOffset!.Value);
        }
    }
    private static nint? _ParticleNumberOffset;

    public CParticleCollectionFloatInput ParticleNumber {
        get {
            _ParticleNumberOffset = _ParticleNumberOffset ?? Schema.GetOffset(0xE4FC739812F26402);
            return new CParticleCollectionFloatInputImpl(_Handle + _ParticleNumberOffset!.Value);
        }
    }
    private static nint? _PinBreakTypeOffset;

    public ref ParticlePinDistance_t PinBreakType {
        get {
            _PinBreakTypeOffset = _PinBreakTypeOffset ?? Schema.GetOffset(0xE4FC73981D66F607);
            return ref _Handle.AsRef<ParticlePinDistance_t>(_PinBreakTypeOffset!.Value);
        }
    }
    private static nint? _BreakDistanceOffset;

    public CParticleCollectionFloatInput BreakDistance {
        get {
            _BreakDistanceOffset = _BreakDistanceOffset ?? Schema.GetOffset(0xE4FC7398AD760DA9);
            return new CParticleCollectionFloatInputImpl(_Handle + _BreakDistanceOffset!.Value);
        }
    }
    private static nint? _BreakSpeedOffset;

    public CParticleCollectionFloatInput BreakSpeed {
        get {
            _BreakSpeedOffset = _BreakSpeedOffset ?? Schema.GetOffset(0xE4FC739817DB9AD5);
            return new CParticleCollectionFloatInputImpl(_Handle + _BreakSpeedOffset!.Value);
        }
    }
    private static nint? _AgeOffset;

    public CParticleCollectionFloatInput Age {
        get {
            _AgeOffset = _AgeOffset ?? Schema.GetOffset(0xE4FC73984F7B4AF6);
            return new CParticleCollectionFloatInputImpl(_Handle + _AgeOffset!.Value);
        }
    }
    private static nint? _BreakControlPointNumberOffset;

    public ref int BreakControlPointNumber {
        get {
            _BreakControlPointNumberOffset = _BreakControlPointNumberOffset ?? Schema.GetOffset(0xE4FC739817C1EFA0);
            return ref _Handle.AsRef<int>(_BreakControlPointNumberOffset!.Value);
        }
    }
    private static nint? _BreakControlPointNumber2Offset;

    public ref int BreakControlPointNumber2 {
        get {
            _BreakControlPointNumber2Offset = _BreakControlPointNumber2Offset ?? Schema.GetOffset(0xE4FC7398F84C22D6);
            return ref _Handle.AsRef<int>(_BreakControlPointNumber2Offset!.Value);
        }
    }
    private static nint? _BreakValueOffset;

    public CParticleCollectionFloatInput BreakValue {
        get {
            _BreakValueOffset = _BreakValueOffset ?? Schema.GetOffset(0xE4FC7398D120F44B);
            return new CParticleCollectionFloatInputImpl(_Handle + _BreakValueOffset!.Value);
        }
    }
    private static nint? _InterpolationOffset;

    public CPerParticleFloatInput Interpolation {
        get {
            _InterpolationOffset = _InterpolationOffset ?? Schema.GetOffset(0xE4FC7398CF55B987);
            return new CPerParticleFloatInputImpl(_Handle + _InterpolationOffset!.Value);
        }
    }
    private static nint? _RetainInitialVelocityOffset;

    public ref bool RetainInitialVelocity {
        get {
            _RetainInitialVelocityOffset = _RetainInitialVelocityOffset ?? Schema.GetOffset(0xE4FC73981B3893D3);
            return ref _Handle.AsRef<bool>(_RetainInitialVelocityOffset!.Value);
        }
    }


}