// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_Orient2DRelToCPImpl : CParticleFunctionOperatorImpl, C_OP_Orient2DRelToCP {

  public C_OP_Orient2DRelToCPImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _RotOffsetOffset = new(() => Schema.GetOffset(0xD330A83D1EA9CDF), LazyThreadSafetyMode.None);

  public ref float RotOffset {
    get => ref _Handle.AsRef<float>(_RotOffsetOffset.Value);
  }
  private static readonly Lazy<nint> _SpinStrengthOffset = new(() => Schema.GetOffset(0xD330A8312520F26), LazyThreadSafetyMode.None);

  public ref float SpinStrength {
    get => ref _Handle.AsRef<float>(_SpinStrengthOffset.Value);
  }
  private static readonly Lazy<nint> _CPOffset = new(() => Schema.GetOffset(0xD330A83EB661472), LazyThreadSafetyMode.None);

  public ref int CP {
    get => ref _Handle.AsRef<int>(_CPOffset.Value);
  }
  private static readonly Lazy<nint> _FieldOutputOffset = new(() => Schema.GetOffset(0xD330A83E5729606), LazyThreadSafetyMode.None);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset.Value);
  }


}