// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RenderStatusEffectCitadelImpl : CParticleFunctionRendererImpl, C_OP_RenderStatusEffectCitadel {

  public C_OP_RenderStatusEffectCitadelImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _TextureColorWarpOffset = new(() => Schema.GetOffset(0x3A3089C2C99DEE43), LazyThreadSafetyMode.None);

  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureColorWarp {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCTextureBase>>(_TextureColorWarpOffset.Value);
  }
  private static readonly Lazy<nint> _TextureNormalOffset = new(() => Schema.GetOffset(0x3A3089C298E8363D), LazyThreadSafetyMode.None);

  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureNormal {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCTextureBase>>(_TextureNormalOffset.Value);
  }
  private static readonly Lazy<nint> _TextureMetalnessOffset = new(() => Schema.GetOffset(0x3A3089C25ABD9B42), LazyThreadSafetyMode.None);

  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureMetalness {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCTextureBase>>(_TextureMetalnessOffset.Value);
  }
  private static readonly Lazy<nint> _TextureRoughnessOffset = new(() => Schema.GetOffset(0x3A3089C2BD0AD95C), LazyThreadSafetyMode.None);

  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureRoughness {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCTextureBase>>(_TextureRoughnessOffset.Value);
  }
  private static readonly Lazy<nint> _TextureSelfIllumOffset = new(() => Schema.GetOffset(0x3A3089C2D815240D), LazyThreadSafetyMode.None);

  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureSelfIllum {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCTextureBase>>(_TextureSelfIllumOffset.Value);
  }
  private static readonly Lazy<nint> _TextureDetailOffset = new(() => Schema.GetOffset(0x3A3089C28D414A8F), LazyThreadSafetyMode.None);

  public ref CStrongHandle<InfoForResourceTypeCTextureBase> TextureDetail {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCTextureBase>>(_TextureDetailOffset.Value);
  }


}