// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapControlPointOrientationToRotationImpl : CParticleFunctionOperatorImpl, C_OP_RemapControlPointOrientationToRotation {

  public C_OP_RemapControlPointOrientationToRotationImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _CPOffset = new(() => Schema.GetOffset(0x2CE44E90EB661472), LazyThreadSafetyMode.None);

  public ref int CP {
    get => ref _Handle.AsRef<int>(_CPOffset.Value);
  }
  private static readonly Lazy<nint> _FieldOutputOffset = new(() => Schema.GetOffset(0x2CE44E90E5729606), LazyThreadSafetyMode.None);

  public ParticleAttributeIndex_t FieldOutput {
    get => new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset.Value);
  }
  private static readonly Lazy<nint> _OffsetRotOffset = new(() => Schema.GetOffset(0x2CE44E90B414F849), LazyThreadSafetyMode.None);

  public ref float OffsetRot {
    get => ref _Handle.AsRef<float>(_OffsetRotOffset.Value);
  }
  private static readonly Lazy<nint> _ComponentOffset = new(() => Schema.GetOffset(0x2CE44E90BFD0952C), LazyThreadSafetyMode.None);

  public ref int Component {
    get => ref _Handle.AsRef<int>(_ComponentOffset.Value);
  }


}