// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_QuantizeFloatImpl : CParticleFunctionOperatorImpl, C_OP_QuantizeFloat {

  public C_OP_QuantizeFloatImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _InputValueOffset = new(() => Schema.GetOffset(0xCD85375434445438), LazyThreadSafetyMode.None);

  public CPerParticleFloatInput InputValue {
    get => new CPerParticleFloatInputImpl(_Handle + _InputValueOffset.Value);
  }
  private static readonly Lazy<nint> _OutputFieldOffset = new(() => Schema.GetOffset(0xCD853754324F6F74), LazyThreadSafetyMode.None);

  public ParticleAttributeIndex_t OutputField {
    get => new ParticleAttributeIndex_tImpl(_Handle + _OutputFieldOffset.Value);
  }


}