// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapControlPointDirectionToVectorImpl : CParticleFunctionOperatorImpl, C_OP_RemapControlPointDirectionToVector
{
    public C_OP_RemapControlPointDirectionToVectorImpl(nint handle) : base(handle) { }

    private static nint? _FieldOutputOffset;

    public ParticleAttributeIndex_t FieldOutput {
        get {
            _FieldOutputOffset = _FieldOutputOffset ?? Schema.GetOffset(0xB5467A62E5729606);
            return new ParticleAttributeIndex_tImpl(_Handle + _FieldOutputOffset!.Value);
        }
    }
    private static nint? _ScaleOffset;

    public ref float Scale {
        get {
            _ScaleOffset = _ScaleOffset ?? Schema.GetOffset(0xB5467A62B731A42F);
            return ref _Handle.AsRef<float>(_ScaleOffset!.Value);
        }
    }
    private static nint? _ControlPointNumberOffset;

    public ref int ControlPointNumber {
        get {
            _ControlPointNumberOffset = _ControlPointNumberOffset ?? Schema.GetOffset(0xB5467A623F31A6BD);
            return ref _Handle.AsRef<int>(_ControlPointNumberOffset!.Value);
        }
    }


}