// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimationGraphVisualizerTextImpl : CAnimationGraphVisualizerPrimitiveBaseImpl, CAnimationGraphVisualizerText {

  public CAnimationGraphVisualizerTextImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _WsPositionOffset = new(() => Schema.GetOffset(0x123E08CFCA77AB88), LazyThreadSafetyMode.None);

  public ref Vector WsPosition {
    get => ref _Handle.AsRef<Vector>(_WsPositionOffset.Value);
  }
  private static readonly Lazy<nint> _ColorOffset = new(() => Schema.GetOffset(0x123E08CFD7D017D8), LazyThreadSafetyMode.None);

  public ref Color Color {
    get => ref _Handle.AsRef<Color>(_ColorOffset.Value);
  }
  private static readonly Lazy<nint> _TextOffset = new(() => Schema.GetOffset(0x123E08CFFB9532BE), LazyThreadSafetyMode.None);

  public string Text {
    get {
      var ptr = _Handle.Read<nint>(_TextOffset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _TextOffset.Value, value);
  } 


}