// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CastSphereSATParams_tImpl : SchemaClass, CastSphereSATParams_t {

  public CastSphereSATParams_tImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _RayStartOffset = new(() => Schema.GetOffset(0x6282EF48CB929F19), LazyThreadSafetyMode.None);

  public ref Vector RayStart {
    get => ref _Handle.AsRef<Vector>(_RayStartOffset.Value);
  }
  private static readonly Lazy<nint> _RayDeltaOffset = new(() => Schema.GetOffset(0x6282EF4874156D5B), LazyThreadSafetyMode.None);

  public ref Vector RayDelta {
    get => ref _Handle.AsRef<Vector>(_RayDeltaOffset.Value);
  }
  private static readonly Lazy<nint> _RadiusOffset = new(() => Schema.GetOffset(0x6282EF485ACFC08D), LazyThreadSafetyMode.None);

  public ref float Radius {
    get => ref _Handle.AsRef<float>(_RadiusOffset.Value);
  }
  private static readonly Lazy<nint> _MaxFractionOffset = new(() => Schema.GetOffset(0x6282EF48BA58C801), LazyThreadSafetyMode.None);

  public ref float MaxFraction {
    get => ref _Handle.AsRef<float>(_MaxFractionOffset.Value);
  }
  private static readonly Lazy<nint> _ScaleOffset = new(() => Schema.GetOffset(0x6282EF48B731A42F), LazyThreadSafetyMode.None);

  public ref float Scale {
    get => ref _Handle.AsRef<float>(_ScaleOffset.Value);
  }
  private static readonly Lazy<nint> _HullOffset = new(() => Schema.GetOffset(0x6282EF48FAD20488), LazyThreadSafetyMode.None);

  public RnHull_t? Hull {
    get {
      var ptr = _Handle.Read<nint>(_HullOffset.Value);
      return ptr.IsValidPtr() ? new RnHull_tImpl(ptr) : null;
    }
  }


}