// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBaseMoveBehaviorImpl : CPathKeyFrameImpl, CBaseMoveBehavior {

  public CBaseMoveBehaviorImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _PositionInterpolatorOffset = new(() => Schema.GetOffset(0x4C94E06076D631CA), LazyThreadSafetyMode.None);

  public ref int PositionInterpolator {
    get => ref _Handle.AsRef<int>(_PositionInterpolatorOffset.Value);
  }
  private static readonly Lazy<nint> _RotationInterpolatorOffset = new(() => Schema.GetOffset(0x4C94E060D5ABDED3), LazyThreadSafetyMode.None);

  public ref int RotationInterpolator {
    get => ref _Handle.AsRef<int>(_RotationInterpolatorOffset.Value);
  }
  private static readonly Lazy<nint> _AnimStartTimeOffset = new(() => Schema.GetOffset(0x4C94E060C2FA1CCF), LazyThreadSafetyMode.None);

  public ref float AnimStartTime {
    get => ref _Handle.AsRef<float>(_AnimStartTimeOffset.Value);
  }
  private static readonly Lazy<nint> _AnimEndTimeOffset = new(() => Schema.GetOffset(0x4C94E06042C3E66A), LazyThreadSafetyMode.None);

  public ref float AnimEndTime {
    get => ref _Handle.AsRef<float>(_AnimEndTimeOffset.Value);
  }
  private static readonly Lazy<nint> _AverageSpeedAcrossFrameOffset = new(() => Schema.GetOffset(0x4C94E0603F4A5B51), LazyThreadSafetyMode.None);

  public ref float AverageSpeedAcrossFrame {
    get => ref _Handle.AsRef<float>(_AverageSpeedAcrossFrameOffset.Value);
  }
  private static readonly Lazy<nint> _CurrentKeyFrameOffset = new(() => Schema.GetOffset(0x4C94E060AF22FD24), LazyThreadSafetyMode.None);

  public CPathKeyFrame? CurrentKeyFrame {
    get {
      var ptr = _Handle.Read<nint>(_CurrentKeyFrameOffset.Value);
      return ptr.IsValidPtr() ? new CPathKeyFrameImpl(ptr) : null;
    }
  }
  private static readonly Lazy<nint> _TargetKeyFrameOffset = new(() => Schema.GetOffset(0x4C94E0606B9E13EA), LazyThreadSafetyMode.None);

  public CPathKeyFrame? TargetKeyFrame {
    get {
      var ptr = _Handle.Read<nint>(_TargetKeyFrameOffset.Value);
      return ptr.IsValidPtr() ? new CPathKeyFrameImpl(ptr) : null;
    }
  }
  private static readonly Lazy<nint> _PreKeyFrameOffset = new(() => Schema.GetOffset(0x4C94E0609753526C), LazyThreadSafetyMode.None);

  public CPathKeyFrame? PreKeyFrame {
    get {
      var ptr = _Handle.Read<nint>(_PreKeyFrameOffset.Value);
      return ptr.IsValidPtr() ? new CPathKeyFrameImpl(ptr) : null;
    }
  }
  private static readonly Lazy<nint> _PostKeyFrameOffset = new(() => Schema.GetOffset(0x4C94E06033EC8ED5), LazyThreadSafetyMode.None);

  public CPathKeyFrame? PostKeyFrame {
    get {
      var ptr = _Handle.Read<nint>(_PostKeyFrameOffset.Value);
      return ptr.IsValidPtr() ? new CPathKeyFrameImpl(ptr) : null;
    }
  }
  private static readonly Lazy<nint> _TimeIntoFrameOffset = new(() => Schema.GetOffset(0x4C94E060C6B111CD), LazyThreadSafetyMode.None);

  public ref float TimeIntoFrame {
    get => ref _Handle.AsRef<float>(_TimeIntoFrameOffset.Value);
  }
  private static readonly Lazy<nint> _DirectionOffset = new(() => Schema.GetOffset(0x4C94E0606BDD23E5), LazyThreadSafetyMode.None);

  public ref int Direction {
    get => ref _Handle.AsRef<int>(_DirectionOffset.Value);
  }


}