// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBuoyancyHelperImpl : SchemaClass, CBuoyancyHelper {

  public CBuoyancyHelperImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _FluidTypeOffset = new(() => Schema.GetOffset(0x7A9E77003D45CF5F), LazyThreadSafetyMode.None);

  public ref CUtlStringToken FluidType {
    get => ref _Handle.AsRef<CUtlStringToken>(_FluidTypeOffset.Value);
  }
  private static readonly Lazy<nint> _FluidDensityOffset = new(() => Schema.GetOffset(0x7A9E7700DABBC5A3), LazyThreadSafetyMode.None);

  public ref float FluidDensity {
    get => ref _Handle.AsRef<float>(_FluidDensityOffset.Value);
  }
  private static readonly Lazy<nint> _NeutrallyBuoyantGravityOffset = new(() => Schema.GetOffset(0x7A9E77007EFB6975), LazyThreadSafetyMode.None);

  public ref float NeutrallyBuoyantGravity {
    get => ref _Handle.AsRef<float>(_NeutrallyBuoyantGravityOffset.Value);
  }
  private static readonly Lazy<nint> _NeutrallyBuoyantLinearDampingOffset = new(() => Schema.GetOffset(0x7A9E7700F2B7E456), LazyThreadSafetyMode.None);

  public ref float NeutrallyBuoyantLinearDamping {
    get => ref _Handle.AsRef<float>(_NeutrallyBuoyantLinearDampingOffset.Value);
  }
  private static readonly Lazy<nint> _NeutrallyBuoyantAngularDampingOffset = new(() => Schema.GetOffset(0x7A9E770013DF82F1), LazyThreadSafetyMode.None);

  public ref float NeutrallyBuoyantAngularDamping {
    get => ref _Handle.AsRef<float>(_NeutrallyBuoyantAngularDampingOffset.Value);
  }
  private static readonly Lazy<nint> _NeutrallyBuoyantOffset = new(() => Schema.GetOffset(0x7A9E7700D0DF6ADF), LazyThreadSafetyMode.None);

  public ref bool NeutrallyBuoyant {
    get => ref _Handle.AsRef<bool>(_NeutrallyBuoyantOffset.Value);
  }
  private static readonly Lazy<nint> _FractionOfWheelSubmergedForWheelFrictionOffset = new(() => Schema.GetOffset(0x7A9E77009D5C3295), LazyThreadSafetyMode.None);

  public ref CUtlVector<float> FractionOfWheelSubmergedForWheelFriction {
    get => ref _Handle.AsRef<CUtlVector<float>>(_FractionOfWheelSubmergedForWheelFrictionOffset.Value);
  }
  private static readonly Lazy<nint> _WheelFrictionScalesOffset = new(() => Schema.GetOffset(0x7A9E77005D5150ED), LazyThreadSafetyMode.None);

  public ref CUtlVector<float> WheelFrictionScales {
    get => ref _Handle.AsRef<CUtlVector<float>>(_WheelFrictionScalesOffset.Value);
  }
  private static readonly Lazy<nint> _FractionOfWheelSubmergedForWheelDragOffset = new(() => Schema.GetOffset(0x7A9E7700E1C2C831), LazyThreadSafetyMode.None);

  public ref CUtlVector<float> FractionOfWheelSubmergedForWheelDrag {
    get => ref _Handle.AsRef<CUtlVector<float>>(_FractionOfWheelSubmergedForWheelDragOffset.Value);
  }
  private static readonly Lazy<nint> _WheelDragOffset = new(() => Schema.GetOffset(0x7A9E7700E95C5D6E), LazyThreadSafetyMode.None);

  public ref CUtlVector<float> WheelDrag {
    get => ref _Handle.AsRef<CUtlVector<float>>(_WheelDragOffset.Value);
  }


}