// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCSPlayer_PingServicesImpl : CPlayerPawnComponentImpl, CCSPlayer_PingServices {

  public CCSPlayer_PingServicesImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _PlayerPingTokensOffset = new(() => Schema.GetOffset(0xC78D79CA55696280), LazyThreadSafetyMode.None);

  public SchemaUntypedField PlayerPingTokens {
    get => new SchemaUntypedField(_Handle + _PlayerPingTokensOffset.Value);
  }
  private static readonly Lazy<nint> _PlayerPingOffset = new(() => Schema.GetOffset(0xC78D79CA464EEA6E), LazyThreadSafetyMode.None);

  public ref CHandle<CPlayerPing> PlayerPing {
    get => ref _Handle.AsRef<CHandle<CPlayerPing>>(_PlayerPingOffset.Value);
  }

  public void PlayerPingUpdated() {
    Schema.Update(_Handle, 0xC78D79CA464EEA6E);
  }
}