// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCSPlayer_ActionTrackingServicesImpl : CPlayerPawnComponentImpl, CCSPlayer_ActionTrackingServices {

  public CCSPlayer_ActionTrackingServicesImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _LastWeaponBeforeC4AutoSwitchOffset = new(() => Schema.GetOffset(0xC890019D6687BAC0), LazyThreadSafetyMode.None);

  public ref CHandle<CBasePlayerWeapon> LastWeaponBeforeC4AutoSwitch {
    get => ref _Handle.AsRef<CHandle<CBasePlayerWeapon>>(_LastWeaponBeforeC4AutoSwitchOffset.Value);
  }
  private static readonly Lazy<nint> _IsRescuingOffset = new(() => Schema.GetOffset(0xC890019D225BDB2F), LazyThreadSafetyMode.None);

  public ref bool IsRescuing {
    get => ref _Handle.AsRef<bool>(_IsRescuingOffset.Value);
  }
  private static readonly Lazy<nint> _WeaponPurchasesThisMatchOffset = new(() => Schema.GetOffset(0xC890019D43F68EE0), LazyThreadSafetyMode.None);

  public WeaponPurchaseTracker_t WeaponPurchasesThisMatch {
    get => new WeaponPurchaseTracker_tImpl(_Handle + _WeaponPurchasesThisMatchOffset.Value);
  }
  private static readonly Lazy<nint> _WeaponPurchasesThisRoundOffset = new(() => Schema.GetOffset(0xC890019D7C64F835), LazyThreadSafetyMode.None);

  public WeaponPurchaseTracker_t WeaponPurchasesThisRound {
    get => new WeaponPurchaseTracker_tImpl(_Handle + _WeaponPurchasesThisRoundOffset.Value);
  }

  public void IsRescuingUpdated() {
    Schema.Update(_Handle, 0xC890019D225BDB2F);
  }
  public void WeaponPurchasesThisMatchUpdated() {
    Schema.Update(_Handle, 0xC890019D43F68EE0);
  }
  public void WeaponPurchasesThisRoundUpdated() {
    Schema.Update(_Handle, 0xC890019D7C64F835);
  }
}