// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CDecalInstanceImpl : SchemaClass, CDecalInstance
{
    public CDecalInstanceImpl(nint handle) : base(handle) { }

    private static nint? _DecalGroupOffset;

    public ref CGlobalSymbol DecalGroup {
        get {
            _DecalGroupOffset = _DecalGroupOffset ?? Schema.GetOffset(0x88CA447CCEBD4836);
            return ref _Handle.AsRef<CGlobalSymbol>(_DecalGroupOffset!.Value);
        }
    }
    private static nint? _MaterialOffset;

    public ref CStrongHandle<InfoForResourceTypeIMaterial2> Material {
        get {
            _MaterialOffset = _MaterialOffset ?? Schema.GetOffset(0x88CA447C888CE42E);
            return ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIMaterial2>>(_MaterialOffset!.Value);
        }
    }
    private static nint? _SequenceNameOffset;

    public ref CUtlStringToken SequenceName {
        get {
            _SequenceNameOffset = _SequenceNameOffset ?? Schema.GetOffset(0x88CA447C7462AF30);
            return ref _Handle.AsRef<CUtlStringToken>(_SequenceNameOffset!.Value);
        }
    }
    private static nint? _EntityOffset;

    public ref CHandle<CBaseEntity> Entity {
        get {
            _EntityOffset = _EntityOffset ?? Schema.GetOffset(0x88CA447C6EBADCB0);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_EntityOffset!.Value);
        }
    }
    private static nint? _BoneIndexOffset;

    public ref int BoneIndex {
        get {
            _BoneIndexOffset = _BoneIndexOffset ?? Schema.GetOffset(0x88CA447C9F407B79);
            return ref _Handle.AsRef<int>(_BoneIndexOffset!.Value);
        }
    }
    private static nint? _TriangleIndexOffset;

    public ref int TriangleIndex {
        get {
            _TriangleIndexOffset = _TriangleIndexOffset ?? Schema.GetOffset(0x88CA447C4465462F);
            return ref _Handle.AsRef<int>(_TriangleIndexOffset!.Value);
        }
    }
    private static nint? _PositionLSOffset;

    public ref Vector PositionLS {
        get {
            _PositionLSOffset = _PositionLSOffset ?? Schema.GetOffset(0x88CA447C9D27001F);
            return ref _Handle.AsRef<Vector>(_PositionLSOffset!.Value);
        }
    }
    private static nint? _NormalLSOffset;

    public ref Vector NormalLS {
        get {
            _NormalLSOffset = _NormalLSOffset ?? Schema.GetOffset(0x88CA447C1C20D7C7);
            return ref _Handle.AsRef<Vector>(_NormalLSOffset!.Value);
        }
    }
    private static nint? _SAxisLSOffset;

    public ref Vector SAxisLS {
        get {
            _SAxisLSOffset = _SAxisLSOffset ?? Schema.GetOffset(0x88CA447C95DE878A);
            return ref _Handle.AsRef<Vector>(_SAxisLSOffset!.Value);
        }
    }
    private static nint? _FlagsOffset;

    public ref DecalFlags_t Flags {
        get {
            _FlagsOffset = _FlagsOffset ?? Schema.GetOffset(0x88CA447CCE6E9C28);
            return ref _Handle.AsRef<DecalFlags_t>(_FlagsOffset!.Value);
        }
    }
    private static nint? _ColorOffset;

    public ref Color Color {
        get {
            _ColorOffset = _ColorOffset ?? Schema.GetOffset(0x88CA447CD7D017D8);
            return ref _Handle.AsRef<Color>(_ColorOffset!.Value);
        }
    }
    private static nint? _WidthOffset;

    public ref float Width {
        get {
            _WidthOffset = _WidthOffset ?? Schema.GetOffset(0x88CA447CB91935E1);
            return ref _Handle.AsRef<float>(_WidthOffset!.Value);
        }
    }
    private static nint? _HeightOffset;

    public ref float Height {
        get {
            _HeightOffset = _HeightOffset ?? Schema.GetOffset(0x88CA447CEADD7FB0);
            return ref _Handle.AsRef<float>(_HeightOffset!.Value);
        }
    }
    private static nint? _DepthOffset;

    public ref float Depth {
        get {
            _DepthOffset = _DepthOffset ?? Schema.GetOffset(0x88CA447CD3AD54E8);
            return ref _Handle.AsRef<float>(_DepthOffset!.Value);
        }
    }
    private static nint? _AnimationScaleOffset;

    public ref float AnimationScale {
        get {
            _AnimationScaleOffset = _AnimationScaleOffset ?? Schema.GetOffset(0x88CA447CE03B2F87);
            return ref _Handle.AsRef<float>(_AnimationScaleOffset!.Value);
        }
    }
    private static nint? _AnimationStartTimeOffset;

    public ref float AnimationStartTime {
        get {
            _AnimationStartTimeOffset = _AnimationStartTimeOffset ?? Schema.GetOffset(0x88CA447CDC58A88C);
            return ref _Handle.AsRef<float>(_AnimationStartTimeOffset!.Value);
        }
    }
    private static nint? _PlaceTimeOffset;

    public GameTime_t PlaceTime {
        get {
            _PlaceTimeOffset = _PlaceTimeOffset ?? Schema.GetOffset(0x88CA447C1103AE77);
            return new GameTime_tImpl(_Handle + _PlaceTimeOffset!.Value);
        }
    }
    private static nint? _FadeStartTimeOffset;

    public ref float FadeStartTime {
        get {
            _FadeStartTimeOffset = _FadeStartTimeOffset ?? Schema.GetOffset(0x88CA447C86B28BFA);
            return ref _Handle.AsRef<float>(_FadeStartTimeOffset!.Value);
        }
    }
    private static nint? _FadeDurationOffset;

    public ref float FadeDuration {
        get {
            _FadeDurationOffset = _FadeDurationOffset ?? Schema.GetOffset(0x88CA447CC4E6DEE1);
            return ref _Handle.AsRef<float>(_FadeDurationOffset!.Value);
        }
    }
    private static nint? _LightingOriginOffsetOffset;

    public ref float LightingOriginOffset {
        get {
            _LightingOriginOffsetOffset = _LightingOriginOffsetOffset ?? Schema.GetOffset(0x88CA447CBB88AF36);
            return ref _Handle.AsRef<float>(_LightingOriginOffsetOffset!.Value);
        }
    }
    private static nint? _BoundingRadiusSqrOffset;

    public ref float BoundingRadiusSqr {
        get {
            _BoundingRadiusSqrOffset = _BoundingRadiusSqrOffset ?? Schema.GetOffset(0x88CA447CEA90D145);
            return ref _Handle.AsRef<float>(_BoundingRadiusSqrOffset!.Value);
        }
    }
    private static nint? _SequenceIndexOffset;

    public ref short SequenceIndex {
        get {
            _SequenceIndexOffset = _SequenceIndexOffset ?? Schema.GetOffset(0x88CA447CF87A9C78);
            return ref _Handle.AsRef<short>(_SequenceIndexOffset!.Value);
        }
    }
    private static nint? _IsAdjacentOffset;

    public ref bool IsAdjacent {
        get {
            _IsAdjacentOffset = _IsAdjacentOffset ?? Schema.GetOffset(0x88CA447C87EAB10F);
            return ref _Handle.AsRef<bool>(_IsAdjacentOffset!.Value);
        }
    }
    private static nint? _DoDecalLightmappingOffset;

    public ref bool DoDecalLightmapping {
        get {
            _DoDecalLightmappingOffset = _DoDecalLightmappingOffset ?? Schema.GetOffset(0x88CA447C8A2CC817);
            return ref _Handle.AsRef<bool>(_DoDecalLightmappingOffset!.Value);
        }
    }
    private static nint? _SkinnedModelModeOffset;

    public ref DecalMode_t SkinnedModelMode {
        get {
            _SkinnedModelModeOffset = _SkinnedModelModeOffset ?? Schema.GetOffset(0x88CA447CFB03C3D7);
            return ref _Handle.AsRef<DecalMode_t>(_SkinnedModelModeOffset!.Value);
        }
    }


}