// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFootCycleDefinitionImpl : SchemaClass, CFootCycleDefinition {

  public CFootCycleDefinitionImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _StancePositionMSOffset = new(() => Schema.GetOffset(0x6D604C9567085F86), LazyThreadSafetyMode.None);

  public ref Vector StancePositionMS {
    get => ref _Handle.AsRef<Vector>(_StancePositionMSOffset.Value);
  }
  private static readonly Lazy<nint> _MidpointPositionMSOffset = new(() => Schema.GetOffset(0x6D604C9553980B1A), LazyThreadSafetyMode.None);

  public ref Vector MidpointPositionMS {
    get => ref _Handle.AsRef<Vector>(_MidpointPositionMSOffset.Value);
  }
  private static readonly Lazy<nint> _StanceDirectionMSOffset = new(() => Schema.GetOffset(0x6D604C95848F3868), LazyThreadSafetyMode.None);

  public ref float StanceDirectionMS {
    get => ref _Handle.AsRef<float>(_StanceDirectionMSOffset.Value);
  }
  private static readonly Lazy<nint> _ToStrideStartPosOffset = new(() => Schema.GetOffset(0x6D604C953F2E1417), LazyThreadSafetyMode.None);

  public ref Vector ToStrideStartPos {
    get => ref _Handle.AsRef<Vector>(_ToStrideStartPosOffset.Value);
  }
  private static readonly Lazy<nint> _StanceCycleOffset = new(() => Schema.GetOffset(0x6D604C954EDCBD91), LazyThreadSafetyMode.None);

  public CAnimCycle StanceCycle {
    get => new CAnimCycleImpl(_Handle + _StanceCycleOffset.Value);
  }
  private static readonly Lazy<nint> _FootLiftCycleOffset = new(() => Schema.GetOffset(0x6D604C9553A7B946), LazyThreadSafetyMode.None);

  public CFootCycle FootLiftCycle {
    get => new CFootCycleImpl(_Handle + _FootLiftCycleOffset.Value);
  }
  private static readonly Lazy<nint> _FootOffCycleOffset = new(() => Schema.GetOffset(0x6D604C959AC5AE30), LazyThreadSafetyMode.None);

  public CFootCycle FootOffCycle {
    get => new CFootCycleImpl(_Handle + _FootOffCycleOffset.Value);
  }
  private static readonly Lazy<nint> _FootStrikeCycleOffset = new(() => Schema.GetOffset(0x6D604C95E4D3DC2B), LazyThreadSafetyMode.None);

  public CFootCycle FootStrikeCycle {
    get => new CFootCycleImpl(_Handle + _FootStrikeCycleOffset.Value);
  }
  private static readonly Lazy<nint> _FootLandCycleOffset = new(() => Schema.GetOffset(0x6D604C954C100B46), LazyThreadSafetyMode.None);

  public CFootCycle FootLandCycle {
    get => new CFootCycleImpl(_Handle + _FootLandCycleOffset.Value);
  }


}