// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFuncShatterglassImpl : CBaseModelEntityImpl, CFuncShatterglass {

  public CFuncShatterglassImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _MatPanelTransformOffset = new(() => Schema.GetOffset(0xB755F0FB82550F23), LazyThreadSafetyMode.None);

  public ref matrix3x4_t MatPanelTransform {
    get => ref _Handle.AsRef<matrix3x4_t>(_MatPanelTransformOffset.Value);
  }
  private static readonly Lazy<nint> _MatPanelTransformWsTempOffset = new(() => Schema.GetOffset(0xB755F0FB74E9192F), LazyThreadSafetyMode.None);

  public ref matrix3x4_t MatPanelTransformWsTemp {
    get => ref _Handle.AsRef<matrix3x4_t>(_MatPanelTransformWsTempOffset.Value);
  }
  private static readonly Lazy<nint> _ShatterGlassShardsOffset = new(() => Schema.GetOffset(0xB755F0FBCC0BC437), LazyThreadSafetyMode.None);

  public ref CUtlVector<uint> ShatterGlassShards {
    get => ref _Handle.AsRef<CUtlVector<uint>>(_ShatterGlassShardsOffset.Value);
  }
  private static readonly Lazy<nint> _PanelSizeOffset = new(() => Schema.GetOffset(0xB755F0FBC54D327C), LazyThreadSafetyMode.None);

  public ref Vector2D PanelSize {
    get => ref _Handle.AsRef<Vector2D>(_PanelSizeOffset.Value);
  }
  private static readonly Lazy<nint> _LastShatterSoundEmitTimeOffset = new(() => Schema.GetOffset(0xB755F0FB1708F9B9), LazyThreadSafetyMode.None);

  public GameTime_t LastShatterSoundEmitTime {
    get => new GameTime_tImpl(_Handle + _LastShatterSoundEmitTimeOffset.Value);
  }
  private static readonly Lazy<nint> _LastCleanupTimeOffset = new(() => Schema.GetOffset(0xB755F0FBB24E6FB0), LazyThreadSafetyMode.None);

  public GameTime_t LastCleanupTime {
    get => new GameTime_tImpl(_Handle + _LastCleanupTimeOffset.Value);
  }
  private static readonly Lazy<nint> _InitAtTimeOffset = new(() => Schema.GetOffset(0xB755F0FBBBC7C1A5), LazyThreadSafetyMode.None);

  public GameTime_t InitAtTime {
    get => new GameTime_tImpl(_Handle + _InitAtTimeOffset.Value);
  }
  private static readonly Lazy<nint> _GlassThicknessOffset = new(() => Schema.GetOffset(0xB755F0FB59A7355D), LazyThreadSafetyMode.None);

  public ref float GlassThickness {
    get => ref _Handle.AsRef<float>(_GlassThicknessOffset.Value);
  }
  private static readonly Lazy<nint> _SpawnInvulnerabilityOffset = new(() => Schema.GetOffset(0xB755F0FB2B3B17C1), LazyThreadSafetyMode.None);

  public ref float SpawnInvulnerability {
    get => ref _Handle.AsRef<float>(_SpawnInvulnerabilityOffset.Value);
  }
  private static readonly Lazy<nint> _BreakSilentOffset = new(() => Schema.GetOffset(0xB755F0FB87C0E711), LazyThreadSafetyMode.None);

  public ref bool BreakSilent {
    get => ref _Handle.AsRef<bool>(_BreakSilentOffset.Value);
  }
  private static readonly Lazy<nint> _BreakShardlessOffset = new(() => Schema.GetOffset(0xB755F0FBC509E199), LazyThreadSafetyMode.None);

  public ref bool BreakShardless {
    get => ref _Handle.AsRef<bool>(_BreakShardlessOffset.Value);
  }
  private static readonly Lazy<nint> _BrokenOffset = new(() => Schema.GetOffset(0xB755F0FB06654200), LazyThreadSafetyMode.None);

  public ref bool Broken {
    get => ref _Handle.AsRef<bool>(_BrokenOffset.Value);
  }
  private static readonly Lazy<nint> _GlassNavIgnoreOffset = new(() => Schema.GetOffset(0xB755F0FBD9034606), LazyThreadSafetyMode.None);

  public ref bool GlassNavIgnore {
    get => ref _Handle.AsRef<bool>(_GlassNavIgnoreOffset.Value);
  }
  private static readonly Lazy<nint> _GlassInFrameOffset = new(() => Schema.GetOffset(0xB755F0FBEB8CF645), LazyThreadSafetyMode.None);

  public ref bool GlassInFrame {
    get => ref _Handle.AsRef<bool>(_GlassInFrameOffset.Value);
  }
  private static readonly Lazy<nint> _StartBrokenOffset = new(() => Schema.GetOffset(0xB755F0FBEA039156), LazyThreadSafetyMode.None);

  public ref bool StartBroken {
    get => ref _Handle.AsRef<bool>(_StartBrokenOffset.Value);
  }
  private static readonly Lazy<nint> _InitialDamageTypeOffset = new(() => Schema.GetOffset(0xB755F0FBED01D1E1), LazyThreadSafetyMode.None);

  public ref byte InitialDamageType {
    get => ref _Handle.AsRef<byte>(_InitialDamageTypeOffset.Value);
  }
  private static readonly Lazy<nint> _DamagePositioningEntityName01Offset = new(() => Schema.GetOffset(0xB755F0FBADF2770D), LazyThreadSafetyMode.None);

  public string DamagePositioningEntityName01 {
    get {
      var ptr = _Handle.Read<nint>(_DamagePositioningEntityName01Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _DamagePositioningEntityName01Offset.Value, value);
  } 
  private static readonly Lazy<nint> _DamagePositioningEntityName02Offset = new(() => Schema.GetOffset(0xB755F0FBAAF27254), LazyThreadSafetyMode.None);

  public string DamagePositioningEntityName02 {
    get {
      var ptr = _Handle.Read<nint>(_DamagePositioningEntityName02Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _DamagePositioningEntityName02Offset.Value, value);
  } 
  private static readonly Lazy<nint> _DamagePositioningEntityName03Offset = new(() => Schema.GetOffset(0xB755F0FBABF273E7), LazyThreadSafetyMode.None);

  public string DamagePositioningEntityName03 {
    get {
      var ptr = _Handle.Read<nint>(_DamagePositioningEntityName03Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _DamagePositioningEntityName03Offset.Value, value);
  } 
  private static readonly Lazy<nint> _DamagePositioningEntityName04Offset = new(() => Schema.GetOffset(0xB755F0FBA8F26F2E), LazyThreadSafetyMode.None);

  public string DamagePositioningEntityName04 {
    get {
      var ptr = _Handle.Read<nint>(_DamagePositioningEntityName04Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _DamagePositioningEntityName04Offset.Value, value);
  } 
  private static readonly Lazy<nint> _InitialDamagePositionsOffset = new(() => Schema.GetOffset(0xB755F0FB6D8C7F56), LazyThreadSafetyMode.None);

  public ref CUtlVector<Vector> InitialDamagePositions {
    get => ref _Handle.AsRef<CUtlVector<Vector>>(_InitialDamagePositionsOffset.Value);
  }
  private static readonly Lazy<nint> _ExtraDamagePositionsOffset = new(() => Schema.GetOffset(0xB755F0FB94D38DA0), LazyThreadSafetyMode.None);

  public ref CUtlVector<Vector> ExtraDamagePositions {
    get => ref _Handle.AsRef<CUtlVector<Vector>>(_ExtraDamagePositionsOffset.Value);
  }
  private static readonly Lazy<nint> _InitialPanelVerticesOffset = new(() => Schema.GetOffset(0xB755F0FB39117F58), LazyThreadSafetyMode.None);

  public ref CUtlVector<Vector4D> InitialPanelVertices {
    get => ref _Handle.AsRef<CUtlVector<Vector4D>>(_InitialPanelVerticesOffset.Value);
  }
  private static readonly Lazy<nint> _OnBrokenOffset = new(() => Schema.GetOffset(0xB755F0FB961F60E5), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnBroken {
    get => new CEntityIOOutputImpl(_Handle + _OnBrokenOffset.Value);
  }
  private static readonly Lazy<nint> _SurfaceTypeOffset = new(() => Schema.GetOffset(0xB755F0FB3A6DDFE7), LazyThreadSafetyMode.None);

  public ref byte SurfaceType {
    get => ref _Handle.AsRef<byte>(_SurfaceTypeOffset.Value);
  }
  private static readonly Lazy<nint> _MaterialDamageBaseOffset = new(() => Schema.GetOffset(0xB755F0FB3000A1C6), LazyThreadSafetyMode.None);

  public ref CStrongHandle<InfoForResourceTypeIMaterial2> MaterialDamageBase {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIMaterial2>>(_MaterialDamageBaseOffset.Value);
  }


}