// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFuncNavObstructionImpl : CBaseModelEntityImpl, CFuncNavObstruction {

  public CFuncNavObstructionImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _DisabledOffset = new(() => Schema.GetOffset(0xCF9A1E413A7C5965), LazyThreadSafetyMode.None);

  public ref bool Disabled {
    get => ref _Handle.AsRef<bool>(_DisabledOffset.Value);
  }
  private static readonly Lazy<nint> _UseAsyncObstacleUpdateOffset = new(() => Schema.GetOffset(0xCF9A1E41094FA698), LazyThreadSafetyMode.None);

  public ref bool UseAsyncObstacleUpdate {
    get => ref _Handle.AsRef<bool>(_UseAsyncObstacleUpdateOffset.Value);
  }


}