// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CItemGenericImpl : CItemImpl, CItemGeneric
{
    public CItemGenericImpl(nint handle) : base(handle) { }

    private static nint? _HasTriggerRadiusOffset;

    public ref bool HasTriggerRadius {
        get {
            _HasTriggerRadiusOffset = _HasTriggerRadiusOffset ?? Schema.GetOffset(0xE5C051B6D8BAB96B);
            return ref _Handle.AsRef<bool>(_HasTriggerRadiusOffset!.Value);
        }
    }
    private static nint? _HasPickupRadiusOffset;

    public ref bool HasPickupRadius {
        get {
            _HasPickupRadiusOffset = _HasPickupRadiusOffset ?? Schema.GetOffset(0xE5C051B6665CA089);
            return ref _Handle.AsRef<bool>(_HasPickupRadiusOffset!.Value);
        }
    }
    private static nint? _PickupRadiusSqrOffset;

    public ref float PickupRadiusSqr {
        get {
            _PickupRadiusSqrOffset = _PickupRadiusSqrOffset ?? Schema.GetOffset(0xE5C051B6B3C8BD69);
            return ref _Handle.AsRef<float>(_PickupRadiusSqrOffset!.Value);
        }
    }
    private static nint? _TriggerRadiusSqrOffset;

    public ref float TriggerRadiusSqr {
        get {
            _TriggerRadiusSqrOffset = _TriggerRadiusSqrOffset ?? Schema.GetOffset(0xE5C051B64E7B40B7);
            return ref _Handle.AsRef<float>(_TriggerRadiusSqrOffset!.Value);
        }
    }
    private static nint? _LastPickupCheckOffset;

    public GameTime_t LastPickupCheck {
        get {
            _LastPickupCheckOffset = _LastPickupCheckOffset ?? Schema.GetOffset(0xE5C051B6CE974DB1);
            return new GameTime_tImpl(_Handle + _LastPickupCheckOffset!.Value);
        }
    }
    private static nint? _PlayerCounterListenerAddedOffset;

    public ref bool PlayerCounterListenerAdded {
        get {
            _PlayerCounterListenerAddedOffset = _PlayerCounterListenerAddedOffset ?? Schema.GetOffset(0xE5C051B6198E288E);
            return ref _Handle.AsRef<bool>(_PlayerCounterListenerAddedOffset!.Value);
        }
    }
    private static nint? _PlayerInTriggerRadiusOffset;

    public ref bool PlayerInTriggerRadius {
        get {
            _PlayerInTriggerRadiusOffset = _PlayerInTriggerRadiusOffset ?? Schema.GetOffset(0xE5C051B66DC39F9F);
            return ref _Handle.AsRef<bool>(_PlayerInTriggerRadiusOffset!.Value);
        }
    }
    private static nint? _SpawnParticleEffectOffset;

    public ref CStrongHandle<InfoForResourceTypeIParticleSystemDefinition> SpawnParticleEffect {
        get {
            _SpawnParticleEffectOffset = _SpawnParticleEffectOffset ?? Schema.GetOffset(0xE5C051B6576146D5);
            return ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIParticleSystemDefinition>>(_SpawnParticleEffectOffset!.Value);
        }
    }
    private static nint? _AmbientSoundEffectOffset;

    public string AmbientSoundEffect {
        get {
            _AmbientSoundEffectOffset = _AmbientSoundEffectOffset ?? Schema.GetOffset(0xE5C051B65DD78861);
            return Schema.GetString(_Handle.Read<nint>(_AmbientSoundEffectOffset!.Value));
        }
        set {
            _AmbientSoundEffectOffset = _AmbientSoundEffectOffset ?? Schema.GetOffset(0xE5C051B65DD78861);
            Schema.SetString(_Handle, _AmbientSoundEffectOffset!.Value, value);
        }
    } 
    private static nint? _AutoStartAmbientSoundOffset;

    public ref bool AutoStartAmbientSound {
        get {
            _AutoStartAmbientSoundOffset = _AutoStartAmbientSoundOffset ?? Schema.GetOffset(0xE5C051B678660D41);
            return ref _Handle.AsRef<bool>(_AutoStartAmbientSoundOffset!.Value);
        }
    }
    private static nint? _SpawnScriptFunctionOffset;

    public string SpawnScriptFunction {
        get {
            _SpawnScriptFunctionOffset = _SpawnScriptFunctionOffset ?? Schema.GetOffset(0xE5C051B6BC2C9805);
            return Schema.GetString(_Handle.Read<nint>(_SpawnScriptFunctionOffset!.Value));
        }
        set {
            _SpawnScriptFunctionOffset = _SpawnScriptFunctionOffset ?? Schema.GetOffset(0xE5C051B6BC2C9805);
            Schema.SetString(_Handle, _SpawnScriptFunctionOffset!.Value, value);
        }
    } 
    private static nint? _PickupParticleEffectOffset;

    public ref CStrongHandle<InfoForResourceTypeIParticleSystemDefinition> PickupParticleEffect {
        get {
            _PickupParticleEffectOffset = _PickupParticleEffectOffset ?? Schema.GetOffset(0xE5C051B6A61E7280);
            return ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIParticleSystemDefinition>>(_PickupParticleEffectOffset!.Value);
        }
    }
    private static nint? _PickupSoundEffectOffset;

    public string PickupSoundEffect {
        get {
            _PickupSoundEffectOffset = _PickupSoundEffectOffset ?? Schema.GetOffset(0xE5C051B6ECB75E7B);
            return Schema.GetString(_Handle.Read<nint>(_PickupSoundEffectOffset!.Value));
        }
        set {
            _PickupSoundEffectOffset = _PickupSoundEffectOffset ?? Schema.GetOffset(0xE5C051B6ECB75E7B);
            Schema.SetString(_Handle, _PickupSoundEffectOffset!.Value, value);
        }
    } 
    private static nint? _PickupScriptFunctionOffset;

    public string PickupScriptFunction {
        get {
            _PickupScriptFunctionOffset = _PickupScriptFunctionOffset ?? Schema.GetOffset(0xE5C051B64242F490);
            return Schema.GetString(_Handle.Read<nint>(_PickupScriptFunctionOffset!.Value));
        }
        set {
            _PickupScriptFunctionOffset = _PickupScriptFunctionOffset ?? Schema.GetOffset(0xE5C051B64242F490);
            Schema.SetString(_Handle, _PickupScriptFunctionOffset!.Value, value);
        }
    } 
    private static nint? _TimeoutParticleEffectOffset;

    public ref CStrongHandle<InfoForResourceTypeIParticleSystemDefinition> TimeoutParticleEffect {
        get {
            _TimeoutParticleEffectOffset = _TimeoutParticleEffectOffset ?? Schema.GetOffset(0xE5C051B6FE95C38D);
            return ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIParticleSystemDefinition>>(_TimeoutParticleEffectOffset!.Value);
        }
    }
    private static nint? _TimeoutSoundEffectOffset;

    public string TimeoutSoundEffect {
        get {
            _TimeoutSoundEffectOffset = _TimeoutSoundEffectOffset ?? Schema.GetOffset(0xE5C051B6F5AD0260);
            return Schema.GetString(_Handle.Read<nint>(_TimeoutSoundEffectOffset!.Value));
        }
        set {
            _TimeoutSoundEffectOffset = _TimeoutSoundEffectOffset ?? Schema.GetOffset(0xE5C051B6F5AD0260);
            Schema.SetString(_Handle, _TimeoutSoundEffectOffset!.Value, value);
        }
    } 
    private static nint? _TimeoutScriptFunctionOffset;

    public string TimeoutScriptFunction {
        get {
            _TimeoutScriptFunctionOffset = _TimeoutScriptFunctionOffset ?? Schema.GetOffset(0xE5C051B6E8BF2F2D);
            return Schema.GetString(_Handle.Read<nint>(_TimeoutScriptFunctionOffset!.Value));
        }
        set {
            _TimeoutScriptFunctionOffset = _TimeoutScriptFunctionOffset ?? Schema.GetOffset(0xE5C051B6E8BF2F2D);
            Schema.SetString(_Handle, _TimeoutScriptFunctionOffset!.Value, value);
        }
    } 
    private static nint? _PickupFilterNameOffset;

    public string PickupFilterName {
        get {
            _PickupFilterNameOffset = _PickupFilterNameOffset ?? Schema.GetOffset(0xE5C051B613C0B032);
            return Schema.GetString(_Handle.Read<nint>(_PickupFilterNameOffset!.Value));
        }
        set {
            _PickupFilterNameOffset = _PickupFilterNameOffset ?? Schema.GetOffset(0xE5C051B613C0B032);
            Schema.SetString(_Handle, _PickupFilterNameOffset!.Value, value);
        }
    } 
    private static nint? _PickupFilterOffset;

    public ref CHandle<CBaseFilter> PickupFilter {
        get {
            _PickupFilterOffset = _PickupFilterOffset ?? Schema.GetOffset(0xE5C051B605240E41);
            return ref _Handle.AsRef<CHandle<CBaseFilter>>(_PickupFilterOffset!.Value);
        }
    }
    private static nint? _OnPickupOffset;

    public ref CEntityIOOutput OnPickup {
        get {
            _OnPickupOffset = _OnPickupOffset ?? Schema.GetOffset(0xE5C051B628BC1F6C);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnPickupOffset!.Value);
        }
    }
    private static nint? _OnTimeoutOffset;

    public ref CEntityIOOutput OnTimeout {
        get {
            _OnTimeoutOffset = _OnTimeoutOffset ?? Schema.GetOffset(0xE5C051B6C5301603);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnTimeoutOffset!.Value);
        }
    }
    private static nint? _OnTriggerStartTouchOffset;

    public ref CEntityIOOutput OnTriggerStartTouch {
        get {
            _OnTriggerStartTouchOffset = _OnTriggerStartTouchOffset ?? Schema.GetOffset(0xE5C051B66E537987);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnTriggerStartTouchOffset!.Value);
        }
    }
    private static nint? _OnTriggerTouchOffset;

    public ref CEntityIOOutput OnTriggerTouch {
        get {
            _OnTriggerTouchOffset = _OnTriggerTouchOffset ?? Schema.GetOffset(0xE5C051B63BCAE033);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnTriggerTouchOffset!.Value);
        }
    }
    private static nint? _OnTriggerEndTouchOffset;

    public ref CEntityIOOutput OnTriggerEndTouch {
        get {
            _OnTriggerEndTouchOffset = _OnTriggerEndTouchOffset ?? Schema.GetOffset(0xE5C051B63DA3CB84);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnTriggerEndTouchOffset!.Value);
        }
    }
    private static nint? _AllowPickupScriptFunctionOffset;

    public string AllowPickupScriptFunction {
        get {
            _AllowPickupScriptFunctionOffset = _AllowPickupScriptFunctionOffset ?? Schema.GetOffset(0xE5C051B6DC2DF75F);
            return Schema.GetString(_Handle.Read<nint>(_AllowPickupScriptFunctionOffset!.Value));
        }
        set {
            _AllowPickupScriptFunctionOffset = _AllowPickupScriptFunctionOffset ?? Schema.GetOffset(0xE5C051B6DC2DF75F);
            Schema.SetString(_Handle, _AllowPickupScriptFunctionOffset!.Value, value);
        }
    } 
    private static nint? _PickupRadiusOffset;

    public ref float PickupRadius {
        get {
            _PickupRadiusOffset = _PickupRadiusOffset ?? Schema.GetOffset(0xE5C051B64EED9A9D);
            return ref _Handle.AsRef<float>(_PickupRadiusOffset!.Value);
        }
    }
    private static nint? _TriggerRadiusOffset;

    public ref float TriggerRadius {
        get {
            _TriggerRadiusOffset = _TriggerRadiusOffset ?? Schema.GetOffset(0xE5C051B6051F7F0F);
            return ref _Handle.AsRef<float>(_TriggerRadiusOffset!.Value);
        }
    }
    private static nint? _TriggerSoundEffectOffset;

    public string TriggerSoundEffect {
        get {
            _TriggerSoundEffectOffset = _TriggerSoundEffectOffset ?? Schema.GetOffset(0xE5C051B67E4EA459);
            return Schema.GetString(_Handle.Read<nint>(_TriggerSoundEffectOffset!.Value));
        }
        set {
            _TriggerSoundEffectOffset = _TriggerSoundEffectOffset ?? Schema.GetOffset(0xE5C051B67E4EA459);
            Schema.SetString(_Handle, _TriggerSoundEffectOffset!.Value, value);
        }
    } 
    private static nint? _GlowWhenInTriggerOffset;

    public ref bool GlowWhenInTrigger {
        get {
            _GlowWhenInTriggerOffset = _GlowWhenInTriggerOffset ?? Schema.GetOffset(0xE5C051B6FCAD755D);
            return ref _Handle.AsRef<bool>(_GlowWhenInTriggerOffset!.Value);
        }
    }
    private static nint? _GlowColorOffset;

    public ref Color GlowColor {
        get {
            _GlowColorOffset = _GlowColorOffset ?? Schema.GetOffset(0xE5C051B674A5EE03);
            return ref _Handle.AsRef<Color>(_GlowColorOffset!.Value);
        }
    }
    private static nint? _UseableOffset;

    public ref bool Useable {
        get {
            _UseableOffset = _UseableOffset ?? Schema.GetOffset(0xE5C051B6E4DBE46C);
            return ref _Handle.AsRef<bool>(_UseableOffset!.Value);
        }
    }
    private static nint? _TriggerHelperOffset;

    public ref CHandle<CItemGenericTriggerHelper> TriggerHelper {
        get {
            _TriggerHelperOffset = _TriggerHelperOffset ?? Schema.GetOffset(0xE5C051B62DCBD7A9);
            return ref _Handle.AsRef<CHandle<CItemGenericTriggerHelper>>(_TriggerHelperOffset!.Value);
        }
    }


}