// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CModelConfigElement_SetMaterialGroupOnAttachedModelsImpl : CModelConfigElementImpl, CModelConfigElement_SetMaterialGroupOnAttachedModels
{
    public CModelConfigElement_SetMaterialGroupOnAttachedModelsImpl(nint handle) : base(handle) { }

    private static nint? _MaterialGroupNameOffset;

    public string MaterialGroupName {
        get {
            _MaterialGroupNameOffset = _MaterialGroupNameOffset ?? Schema.GetOffset(0xAD67B617C2DD3048);
            return Schema.GetString(_Handle.Read<nint>(_MaterialGroupNameOffset!.Value));
        }
        set {
            _MaterialGroupNameOffset = _MaterialGroupNameOffset ?? Schema.GetOffset(0xAD67B617C2DD3048);
            Schema.SetString(_Handle, _MaterialGroupNameOffset!.Value, value);
        }
    } 


}