// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CModelConfigElement_UserPickImpl : CModelConfigElementImpl, CModelConfigElement_UserPick {

  public CModelConfigElement_UserPickImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _ChoicesOffset = new(() => Schema.GetOffset(0x9AB617A69E9959BF), LazyThreadSafetyMode.None);

  public ref CUtlVector<CUtlString> Choices {
    get => ref _Handle.AsRef<CUtlVector<CUtlString>>(_ChoicesOffset.Value);
  }


}