// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMotionNodeSequenceImpl : CMotionNodeImpl, CMotionNodeSequence {

  public CMotionNodeSequenceImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _TagsOffset = new(() => Schema.GetOffset(0xA932DE59B46C8540), LazyThreadSafetyMode.None);

  public ref CUtlVector<TagSpan_t> Tags {
    get => ref _Handle.AsRef<CUtlVector<TagSpan_t>>(_TagsOffset.Value);
  }
  private static readonly Lazy<nint> _SequenceOffset = new(() => Schema.GetOffset(0xA932DE59E0A0598E), LazyThreadSafetyMode.None);

  public HSequence Sequence {
    get => new HSequenceImpl(_Handle + _SequenceOffset.Value);
  }
  private static readonly Lazy<nint> _PlaybackSpeedOffset = new(() => Schema.GetOffset(0xA932DE59FA2B402D), LazyThreadSafetyMode.None);

  public ref float PlaybackSpeed {
    get => ref _Handle.AsRef<float>(_PlaybackSpeedOffset.Value);
  }


}