// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNetworkOriginQuantizedVectorImpl : SchemaClass, CNetworkOriginQuantizedVector {

  public CNetworkOriginQuantizedVectorImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _XOffset = new(() => Schema.GetOffset(0xB34626888FEB7867), LazyThreadSafetyMode.None);

  public ref CNetworkedQuantizedFloat X {
    get => ref _Handle.AsRef<CNetworkedQuantizedFloat>(_XOffset.Value);
  }
  private static readonly Lazy<nint> _YOffset = new(() => Schema.GetOffset(0xB34626888EEB76D4), LazyThreadSafetyMode.None);

  public ref CNetworkedQuantizedFloat Y {
    get => ref _Handle.AsRef<CNetworkedQuantizedFloat>(_YOffset.Value);
  }
  private static readonly Lazy<nint> _ZOffset = new(() => Schema.GetOffset(0xB346268891EB7B8D), LazyThreadSafetyMode.None);

  public ref CNetworkedQuantizedFloat Z {
    get => ref _Handle.AsRef<CNetworkedQuantizedFloat>(_ZOffset.Value);
  }

  public void XUpdated() {
    Schema.Update(_Handle, 0xB34626888FEB7867);
  }
  public void YUpdated() {
    Schema.Update(_Handle, 0xB34626888EEB76D4);
  }
  public void ZUpdated() {
    Schema.Update(_Handle, 0xB346268891EB7B8D);
  }
}