// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmAimCSNode__CDefinitionImpl : CNmPassthroughNode__CDefinitionImpl, CNmAimCSNode__CDefinition {

  public CNmAimCSNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _VerticalAngleNodeIdxOffset = new(() => Schema.GetOffset(0xE1CD14C20A1F17AD), LazyThreadSafetyMode.None);

  public ref short VerticalAngleNodeIdx {
    get => ref _Handle.AsRef<short>(_VerticalAngleNodeIdxOffset.Value);
  }
  private static readonly Lazy<nint> _HorizontalAngleNodeIdxOffset = new(() => Schema.GetOffset(0xE1CD14C28E2FD3DB), LazyThreadSafetyMode.None);

  public ref short HorizontalAngleNodeIdx {
    get => ref _Handle.AsRef<short>(_HorizontalAngleNodeIdxOffset.Value);
  }
  private static readonly Lazy<nint> _WeaponCategoryNodeIdxOffset = new(() => Schema.GetOffset(0xE1CD14C216D198E4), LazyThreadSafetyMode.None);

  public ref short WeaponCategoryNodeIdx {
    get => ref _Handle.AsRef<short>(_WeaponCategoryNodeIdxOffset.Value);
  }
  private static readonly Lazy<nint> _EnabledNodeIdxOffset = new(() => Schema.GetOffset(0xE1CD14C2F7CDF5E9), LazyThreadSafetyMode.None);

  public ref short EnabledNodeIdx {
    get => ref _Handle.AsRef<short>(_EnabledNodeIdxOffset.Value);
  }
  private static readonly Lazy<nint> _BlendTimeSecondsOffset = new(() => Schema.GetOffset(0xE1CD14C26D3A08FC), LazyThreadSafetyMode.None);

  public ref float BlendTimeSeconds {
    get => ref _Handle.AsRef<float>(_BlendTimeSecondsOffset.Value);
  }


}