// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmConstBoolNode__CDefinitionImpl : CNmBoolValueNode__CDefinitionImpl, CNmConstBoolNode__CDefinition
{
    public CNmConstBoolNode__CDefinitionImpl(nint handle) : base(handle) { }

    private static nint? _ValueOffset;

    public ref bool Value {
        get {
            _ValueOffset = _ValueOffset ?? Schema.GetOffset(0xDEAA315605AAB4AA);
            return ref _Handle.AsRef<bool>(_ValueOffset!.Value);
        }
    }


}