// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmFloatRangeComparisonNode__CDefinitionImpl : CNmBoolValueNode__CDefinitionImpl, CNmFloatRangeComparisonNode__CDefinition {

  public CNmFloatRangeComparisonNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _RangeOffset = new(() => Schema.GetOffset(0x6F364CB3D639CF2), LazyThreadSafetyMode.None);

  public SchemaUntypedField Range {
    get => new SchemaUntypedField(_Handle + _RangeOffset.Value);
  }
  private static readonly Lazy<nint> _InputValueNodeIdxOffset = new(() => Schema.GetOffset(0x6F364CB95E89F27), LazyThreadSafetyMode.None);

  public ref short InputValueNodeIdx {
    get => ref _Handle.AsRef<short>(_InputValueNodeIdxOffset.Value);
  }
  private static readonly Lazy<nint> _IsInclusiveCheckOffset = new(() => Schema.GetOffset(0x6F364CBA95FA7C3), LazyThreadSafetyMode.None);

  public ref bool IsInclusiveCheck {
    get => ref _Handle.AsRef<bool>(_IsInclusiveCheckOffset.Value);
  }


}