// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmPoseNode__CDefinitionImpl : CNmGraphNode__CDefinitionImpl, CNmPoseNode__CDefinition {

  public CNmPoseNode__CDefinitionImpl(nint handle) : base(handle) {
  }




}