// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmSyncEventIndexConditionNode__CDefinitionImpl : CNmBoolValueNode__CDefinitionImpl, CNmSyncEventIndexConditionNode__CDefinition {

  public CNmSyncEventIndexConditionNode__CDefinitionImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _SourceStateNodeIdxOffset = new(() => Schema.GetOffset(0x343CD5DB63F0228C), LazyThreadSafetyMode.None);

  public ref short SourceStateNodeIdx {
    get => ref _Handle.AsRef<short>(_SourceStateNodeIdxOffset.Value);
  }
  private static readonly Lazy<nint> _TriggerModeOffset = new(() => Schema.GetOffset(0x343CD5DB0431A60C), LazyThreadSafetyMode.None);

  public ref CNmSyncEventIndexConditionNode__TriggerMode_t TriggerMode {
    get => ref _Handle.AsRef<CNmSyncEventIndexConditionNode__TriggerMode_t>(_TriggerModeOffset.Value);
  }
  private static readonly Lazy<nint> _SyncEventIdxOffset = new(() => Schema.GetOffset(0x343CD5DBC84F66C9), LazyThreadSafetyMode.None);

  public ref int SyncEventIdx {
    get => ref _Handle.AsRef<int>(_SyncEventIdxOffset.Value);
  }


}