// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmSkeleton__SecondarySkeleton_tImpl : SchemaClass, CNmSkeleton__SecondarySkeleton_t {

  public CNmSkeleton__SecondarySkeleton_tImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _AttachToBoneIDOffset = new(() => Schema.GetOffset(0x50F456DAB2F06B3A), LazyThreadSafetyMode.None);

  public ref CGlobalSymbol AttachToBoneID {
    get => ref _Handle.AsRef<CGlobalSymbol>(_AttachToBoneIDOffset.Value);
  }
  private static readonly Lazy<nint> _SkeletonOffset = new(() => Schema.GetOffset(0x50F456DAE77F030E), LazyThreadSafetyMode.None);

  public ref CStrongHandle<InfoForResourceTypeCNmSkeleton> Skeleton {
    get => ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCNmSkeleton>>(_SkeletonOffset.Value);
  }


}