// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmVirtualParameterVectorNode__CDefinitionImpl : CNmVectorValueNode__CDefinitionImpl, CNmVirtualParameterVectorNode__CDefinition
{
    public CNmVirtualParameterVectorNode__CDefinitionImpl(nint handle) : base(handle) { }

    private static nint? _ChildNodeIdxOffset;

    public ref short ChildNodeIdx {
        get {
            _ChildNodeIdxOffset = _ChildNodeIdxOffset ?? Schema.GetOffset(0xDD34E2D25C29A73C);
            return ref _Handle.AsRef<short>(_ChildNodeIdxOffset!.Value);
        }
    }


}