// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPointCameraImpl : CBaseEntityImpl, CPointCamera {

  public CPointCameraImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _FOVOffset = new(() => Schema.GetOffset(0x3E5CC0835C3A63DC), LazyThreadSafetyMode.None);

  public ref float FOV {
    get => ref _Handle.AsRef<float>(_FOVOffset.Value);
  }
  private static readonly Lazy<nint> _ResolutionOffset = new(() => Schema.GetOffset(0x3E5CC083B9351D0F), LazyThreadSafetyMode.None);

  public ref float Resolution {
    get => ref _Handle.AsRef<float>(_ResolutionOffset.Value);
  }
  private static readonly Lazy<nint> _FogEnableOffset = new(() => Schema.GetOffset(0x3E5CC0837ED6A448), LazyThreadSafetyMode.None);

  public ref bool FogEnable {
    get => ref _Handle.AsRef<bool>(_FogEnableOffset.Value);
  }
  private static readonly Lazy<nint> _FogColorOffset = new(() => Schema.GetOffset(0x3E5CC083C5585AAE), LazyThreadSafetyMode.None);

  public ref Color FogColor {
    get => ref _Handle.AsRef<Color>(_FogColorOffset.Value);
  }
  private static readonly Lazy<nint> _FogStartOffset = new(() => Schema.GetOffset(0x3E5CC0832A8DE023), LazyThreadSafetyMode.None);

  public ref float FogStart {
    get => ref _Handle.AsRef<float>(_FogStartOffset.Value);
  }
  private static readonly Lazy<nint> _FogEndOffset = new(() => Schema.GetOffset(0x3E5CC08334D4BC16), LazyThreadSafetyMode.None);

  public ref float FogEnd {
    get => ref _Handle.AsRef<float>(_FogEndOffset.Value);
  }
  private static readonly Lazy<nint> _FogMaxDensityOffset = new(() => Schema.GetOffset(0x3E5CC08343CD4C8B), LazyThreadSafetyMode.None);

  public ref float FogMaxDensity {
    get => ref _Handle.AsRef<float>(_FogMaxDensityOffset.Value);
  }
  private static readonly Lazy<nint> _ActiveOffset = new(() => Schema.GetOffset(0x3E5CC0838334208F), LazyThreadSafetyMode.None);

  public ref bool Active {
    get => ref _Handle.AsRef<bool>(_ActiveOffset.Value);
  }
  private static readonly Lazy<nint> _UseScreenAspectRatioOffset = new(() => Schema.GetOffset(0x3E5CC08353101AA3), LazyThreadSafetyMode.None);

  public ref bool UseScreenAspectRatio {
    get => ref _Handle.AsRef<bool>(_UseScreenAspectRatioOffset.Value);
  }
  private static readonly Lazy<nint> _AspectRatioOffset = new(() => Schema.GetOffset(0x3E5CC08381C7922E), LazyThreadSafetyMode.None);

  public ref float AspectRatio {
    get => ref _Handle.AsRef<float>(_AspectRatioOffset.Value);
  }
  private static readonly Lazy<nint> _NoSkyOffset = new(() => Schema.GetOffset(0x3E5CC083760FF03B), LazyThreadSafetyMode.None);

  public ref bool NoSky {
    get => ref _Handle.AsRef<bool>(_NoSkyOffset.Value);
  }
  private static readonly Lazy<nint> _BrightnessOffset = new(() => Schema.GetOffset(0x3E5CC0832E2B25BE), LazyThreadSafetyMode.None);

  public ref float Brightness {
    get => ref _Handle.AsRef<float>(_BrightnessOffset.Value);
  }
  private static readonly Lazy<nint> _ZFarOffset = new(() => Schema.GetOffset(0x3E5CC083578834A4), LazyThreadSafetyMode.None);

  public ref float ZFar {
    get => ref _Handle.AsRef<float>(_ZFarOffset.Value);
  }
  private static readonly Lazy<nint> _ZNearOffset = new(() => Schema.GetOffset(0x3E5CC083C81DED31), LazyThreadSafetyMode.None);

  public ref float ZNear {
    get => ref _Handle.AsRef<float>(_ZNearOffset.Value);
  }
  private static readonly Lazy<nint> _CanHLTVUseOffset = new(() => Schema.GetOffset(0x3E5CC083EF15745A), LazyThreadSafetyMode.None);

  public ref bool CanHLTVUse {
    get => ref _Handle.AsRef<bool>(_CanHLTVUseOffset.Value);
  }
  private static readonly Lazy<nint> _AlignWithParentOffset = new(() => Schema.GetOffset(0x3E5CC08371E0F322), LazyThreadSafetyMode.None);

  public ref bool AlignWithParent {
    get => ref _Handle.AsRef<bool>(_AlignWithParentOffset.Value);
  }
  private static readonly Lazy<nint> _DofEnabledOffset = new(() => Schema.GetOffset(0x3E5CC083EDC8F923), LazyThreadSafetyMode.None);

  public ref bool DofEnabled {
    get => ref _Handle.AsRef<bool>(_DofEnabledOffset.Value);
  }
  private static readonly Lazy<nint> _DofNearBlurryOffset = new(() => Schema.GetOffset(0x3E5CC0837C69D002), LazyThreadSafetyMode.None);

  public ref float DofNearBlurry {
    get => ref _Handle.AsRef<float>(_DofNearBlurryOffset.Value);
  }
  private static readonly Lazy<nint> _DofNearCrispOffset = new(() => Schema.GetOffset(0x3E5CC083B0E97BC1), LazyThreadSafetyMode.None);

  public ref float DofNearCrisp {
    get => ref _Handle.AsRef<float>(_DofNearCrispOffset.Value);
  }
  private static readonly Lazy<nint> _DofFarCrispOffset = new(() => Schema.GetOffset(0x3E5CC0832EC98B88), LazyThreadSafetyMode.None);

  public ref float DofFarCrisp {
    get => ref _Handle.AsRef<float>(_DofFarCrispOffset.Value);
  }
  private static readonly Lazy<nint> _DofFarBlurryOffset = new(() => Schema.GetOffset(0x3E5CC083312C6605), LazyThreadSafetyMode.None);

  public ref float DofFarBlurry {
    get => ref _Handle.AsRef<float>(_DofFarBlurryOffset.Value);
  }
  private static readonly Lazy<nint> _DofTiltToGroundOffset = new(() => Schema.GetOffset(0x3E5CC0833DF50E81), LazyThreadSafetyMode.None);

  public ref float DofTiltToGround {
    get => ref _Handle.AsRef<float>(_DofTiltToGroundOffset.Value);
  }
  private static readonly Lazy<nint> _TargetFOVOffset = new(() => Schema.GetOffset(0x3E5CC0835BA7ABEB), LazyThreadSafetyMode.None);

  public ref float TargetFOV {
    get => ref _Handle.AsRef<float>(_TargetFOVOffset.Value);
  }
  private static readonly Lazy<nint> _DegreesPerSecondOffset = new(() => Schema.GetOffset(0x3E5CC083469C1605), LazyThreadSafetyMode.None);

  public ref float DegreesPerSecond {
    get => ref _Handle.AsRef<float>(_DegreesPerSecondOffset.Value);
  }
  private static readonly Lazy<nint> _IsOnOffset = new(() => Schema.GetOffset(0x3E5CC0836387DB60), LazyThreadSafetyMode.None);

  public ref bool IsOn {
    get => ref _Handle.AsRef<bool>(_IsOnOffset.Value);
  }
  private static readonly Lazy<nint> _NextOffset = new(() => Schema.GetOffset(0x3E5CC08332B11E0E), LazyThreadSafetyMode.None);

  public CPointCamera? Next {
    get {
      var ptr = _Handle.Read<nint>(_NextOffset.Value);
      return ptr.IsValidPtr() ? new CPointCameraImpl(ptr) : null;
    }
  }

  public void FOVUpdated() {
    Schema.Update(_Handle, 0x3E5CC0835C3A63DC);
  }
  public void ResolutionUpdated() {
    Schema.Update(_Handle, 0x3E5CC083B9351D0F);
  }
  public void FogEnableUpdated() {
    Schema.Update(_Handle, 0x3E5CC0837ED6A448);
  }
  public void FogColorUpdated() {
    Schema.Update(_Handle, 0x3E5CC083C5585AAE);
  }
  public void FogStartUpdated() {
    Schema.Update(_Handle, 0x3E5CC0832A8DE023);
  }
  public void FogEndUpdated() {
    Schema.Update(_Handle, 0x3E5CC08334D4BC16);
  }
  public void FogMaxDensityUpdated() {
    Schema.Update(_Handle, 0x3E5CC08343CD4C8B);
  }
  public void ActiveUpdated() {
    Schema.Update(_Handle, 0x3E5CC0838334208F);
  }
  public void UseScreenAspectRatioUpdated() {
    Schema.Update(_Handle, 0x3E5CC08353101AA3);
  }
  public void AspectRatioUpdated() {
    Schema.Update(_Handle, 0x3E5CC08381C7922E);
  }
  public void NoSkyUpdated() {
    Schema.Update(_Handle, 0x3E5CC083760FF03B);
  }
  public void BrightnessUpdated() {
    Schema.Update(_Handle, 0x3E5CC0832E2B25BE);
  }
  public void ZFarUpdated() {
    Schema.Update(_Handle, 0x3E5CC083578834A4);
  }
  public void ZNearUpdated() {
    Schema.Update(_Handle, 0x3E5CC083C81DED31);
  }
  public void CanHLTVUseUpdated() {
    Schema.Update(_Handle, 0x3E5CC083EF15745A);
  }
  public void AlignWithParentUpdated() {
    Schema.Update(_Handle, 0x3E5CC08371E0F322);
  }
  public void DofEnabledUpdated() {
    Schema.Update(_Handle, 0x3E5CC083EDC8F923);
  }
  public void DofNearBlurryUpdated() {
    Schema.Update(_Handle, 0x3E5CC0837C69D002);
  }
  public void DofNearCrispUpdated() {
    Schema.Update(_Handle, 0x3E5CC083B0E97BC1);
  }
  public void DofFarCrispUpdated() {
    Schema.Update(_Handle, 0x3E5CC0832EC98B88);
  }
  public void DofFarBlurryUpdated() {
    Schema.Update(_Handle, 0x3E5CC083312C6605);
  }
  public void DofTiltToGroundUpdated() {
    Schema.Update(_Handle, 0x3E5CC0833DF50E81);
  }
}