// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CRandomNumberGeneratorParametersImpl : SchemaClass, CRandomNumberGeneratorParameters {

  public CRandomNumberGeneratorParametersImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _DistributeEvenlyOffset = new(() => Schema.GetOffset(0x60FDB8F9BED90721), LazyThreadSafetyMode.None);

  public ref bool DistributeEvenly {
    get => ref _Handle.AsRef<bool>(_DistributeEvenlyOffset.Value);
  }
  private static readonly Lazy<nint> _SeedOffset = new(() => Schema.GetOffset(0x60FDB8F99A113550), LazyThreadSafetyMode.None);

  public ref int Seed {
    get => ref _Handle.AsRef<int>(_SeedOffset.Value);
  }


}