// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSceneEntityImpl : CPointEntityImpl, CSceneEntity {

  public CSceneEntityImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _SceneFileOffset = new(() => Schema.GetOffset(0x1099B7011ED89EC5), LazyThreadSafetyMode.None);

  public string SceneFile {
    get {
      var ptr = _Handle.Read<nint>(_SceneFileOffset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _SceneFileOffset.Value, value);
  } 
  private static readonly Lazy<nint> _ResumeSceneFileOffset = new(() => Schema.GetOffset(0x1099B701B722F1C4), LazyThreadSafetyMode.None);

  public string ResumeSceneFile {
    get {
      var ptr = _Handle.Read<nint>(_ResumeSceneFileOffset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ResumeSceneFileOffset.Value, value);
  } 
  private static readonly Lazy<nint> _Target1Offset = new(() => Schema.GetOffset(0x1099B701FC55D183), LazyThreadSafetyMode.None);

  public string Target1 {
    get {
      var ptr = _Handle.Read<nint>(_Target1Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _Target1Offset.Value, value);
  } 
  private static readonly Lazy<nint> _Target2Offset = new(() => Schema.GetOffset(0x1099B701FD55D316), LazyThreadSafetyMode.None);

  public string Target2 {
    get {
      var ptr = _Handle.Read<nint>(_Target2Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _Target2Offset.Value, value);
  } 
  private static readonly Lazy<nint> _Target3Offset = new(() => Schema.GetOffset(0x1099B701FE55D4A9), LazyThreadSafetyMode.None);

  public string Target3 {
    get {
      var ptr = _Handle.Read<nint>(_Target3Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _Target3Offset.Value, value);
  } 
  private static readonly Lazy<nint> _Target4Offset = new(() => Schema.GetOffset(0x1099B701FF55D63C), LazyThreadSafetyMode.None);

  public string Target4 {
    get {
      var ptr = _Handle.Read<nint>(_Target4Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _Target4Offset.Value, value);
  } 
  private static readonly Lazy<nint> _Target5Offset = new(() => Schema.GetOffset(0x1099B7010055D7CF), LazyThreadSafetyMode.None);

  public string Target5 {
    get {
      var ptr = _Handle.Read<nint>(_Target5Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _Target5Offset.Value, value);
  } 
  private static readonly Lazy<nint> _Target6Offset = new(() => Schema.GetOffset(0x1099B7010155D962), LazyThreadSafetyMode.None);

  public string Target6 {
    get {
      var ptr = _Handle.Read<nint>(_Target6Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _Target6Offset.Value, value);
  } 
  private static readonly Lazy<nint> _Target7Offset = new(() => Schema.GetOffset(0x1099B7010255DAF5), LazyThreadSafetyMode.None);

  public string Target7 {
    get {
      var ptr = _Handle.Read<nint>(_Target7Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _Target7Offset.Value, value);
  } 
  private static readonly Lazy<nint> _Target8Offset = new(() => Schema.GetOffset(0x1099B7010355DC88), LazyThreadSafetyMode.None);

  public string Target8 {
    get {
      var ptr = _Handle.Read<nint>(_Target8Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _Target8Offset.Value, value);
  } 
  private static readonly Lazy<nint> _Target11Offset = new(() => Schema.GetOffset(0x1099B701C951F3B1), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> Target11 {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_Target11Offset.Value);
  }
  private static readonly Lazy<nint> _Target22Offset = new(() => Schema.GetOffset(0x1099B701C651EEF8), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> Target22 {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_Target22Offset.Value);
  }
  private static readonly Lazy<nint> _Target33Offset = new(() => Schema.GetOffset(0x1099B701C751F08B), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> Target33 {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_Target33Offset.Value);
  }
  private static readonly Lazy<nint> _Target44Offset = new(() => Schema.GetOffset(0x1099B701CC51F86A), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> Target44 {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_Target44Offset.Value);
  }
  private static readonly Lazy<nint> _Target55Offset = new(() => Schema.GetOffset(0x1099B701CD51F9FD), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> Target55 {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_Target55Offset.Value);
  }
  private static readonly Lazy<nint> _Target66Offset = new(() => Schema.GetOffset(0x1099B701CA51F544), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> Target66 {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_Target66Offset.Value);
  }
  private static readonly Lazy<nint> _Target77Offset = new(() => Schema.GetOffset(0x1099B701CB51F6D7), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> Target77 {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_Target77Offset.Value);
  }
  private static readonly Lazy<nint> _Target88Offset = new(() => Schema.GetOffset(0x1099B701C051E586), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> Target88 {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_Target88Offset.Value);
  }
  private static readonly Lazy<nint> _TargetAttachmentOffset = new(() => Schema.GetOffset(0x1099B701FCD6246E), LazyThreadSafetyMode.None);

  public string TargetAttachment {
    get {
      var ptr = _Handle.Read<nint>(_TargetAttachmentOffset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _TargetAttachmentOffset.Value, value);
  } 
  private static readonly Lazy<nint> _IsPlayingBackOffset = new(() => Schema.GetOffset(0x1099B70133D9EB62), LazyThreadSafetyMode.None);

  public ref bool IsPlayingBack {
    get => ref _Handle.AsRef<bool>(_IsPlayingBackOffset.Value);
  }
  private static readonly Lazy<nint> _PausedOffset = new(() => Schema.GetOffset(0x1099B7016E4C592B), LazyThreadSafetyMode.None);

  public ref bool Paused {
    get => ref _Handle.AsRef<bool>(_PausedOffset.Value);
  }
  private static readonly Lazy<nint> _MultiplayerOffset = new(() => Schema.GetOffset(0x1099B70140E33A8B), LazyThreadSafetyMode.None);

  public ref bool Multiplayer {
    get => ref _Handle.AsRef<bool>(_MultiplayerOffset.Value);
  }
  private static readonly Lazy<nint> _AutogeneratedOffset = new(() => Schema.GetOffset(0x1099B701CD800D57), LazyThreadSafetyMode.None);

  public ref bool Autogenerated {
    get => ref _Handle.AsRef<bool>(_AutogeneratedOffset.Value);
  }
  private static readonly Lazy<nint> _ForceClientTimeOffset = new(() => Schema.GetOffset(0x1099B7010AE43350), LazyThreadSafetyMode.None);

  public ref float ForceClientTime {
    get => ref _Handle.AsRef<float>(_ForceClientTimeOffset.Value);
  }
  private static readonly Lazy<nint> _CurrentTimeOffset = new(() => Schema.GetOffset(0x1099B701C4610999), LazyThreadSafetyMode.None);

  public ref float CurrentTime {
    get => ref _Handle.AsRef<float>(_CurrentTimeOffset.Value);
  }
  private static readonly Lazy<nint> _FrameTimeOffset = new(() => Schema.GetOffset(0x1099B701659DF875), LazyThreadSafetyMode.None);

  public ref float FrameTime {
    get => ref _Handle.AsRef<float>(_FrameTimeOffset.Value);
  }
  private static readonly Lazy<nint> _CancelAtNextInterruptOffset = new(() => Schema.GetOffset(0x1099B70136826B5E), LazyThreadSafetyMode.None);

  public ref bool CancelAtNextInterrupt {
    get => ref _Handle.AsRef<bool>(_CancelAtNextInterruptOffset.Value);
  }
  private static readonly Lazy<nint> _PitchOffset = new(() => Schema.GetOffset(0x1099B701C2997925), LazyThreadSafetyMode.None);

  public ref float Pitch {
    get => ref _Handle.AsRef<float>(_PitchOffset.Value);
  }
  private static readonly Lazy<nint> _AutomatedOffset = new(() => Schema.GetOffset(0x1099B7012F7E23ED), LazyThreadSafetyMode.None);

  public ref bool Automated {
    get => ref _Handle.AsRef<bool>(_AutomatedOffset.Value);
  }
  private static readonly Lazy<nint> _AutomatedActionOffset = new(() => Schema.GetOffset(0x1099B701249A46FB), LazyThreadSafetyMode.None);

  public ref int AutomatedAction {
    get => ref _Handle.AsRef<int>(_AutomatedActionOffset.Value);
  }
  private static readonly Lazy<nint> _AutomationDelayOffset = new(() => Schema.GetOffset(0x1099B701DBCC1E77), LazyThreadSafetyMode.None);

  public ref float AutomationDelay {
    get => ref _Handle.AsRef<float>(_AutomationDelayOffset.Value);
  }
  private static readonly Lazy<nint> _AutomationTimeOffset = new(() => Schema.GetOffset(0x1099B70111D56B91), LazyThreadSafetyMode.None);

  public ref float AutomationTime {
    get => ref _Handle.AsRef<float>(_AutomationTimeOffset.Value);
  }
  private static readonly Lazy<nint> _SpeechPriorityOffset = new(() => Schema.GetOffset(0x1099B701A055E60B), LazyThreadSafetyMode.None);

  public ref int SpeechPriority {
    get => ref _Handle.AsRef<int>(_SpeechPriorityOffset.Value);
  }
  private static readonly Lazy<nint> _WaitingForThisResumeSceneOffset = new(() => Schema.GetOffset(0x1099B7011B4B617A), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> WaitingForThisResumeScene {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_WaitingForThisResumeSceneOffset.Value);
  }
  private static readonly Lazy<nint> _WaitingForResumeSceneOffset = new(() => Schema.GetOffset(0x1099B701F33D29C4), LazyThreadSafetyMode.None);

  public ref bool WaitingForResumeScene {
    get => ref _Handle.AsRef<bool>(_WaitingForResumeSceneOffset.Value);
  }
  private static readonly Lazy<nint> _PausedViaInputOffset = new(() => Schema.GetOffset(0x1099B70194DAAEC7), LazyThreadSafetyMode.None);

  public ref bool PausedViaInput {
    get => ref _Handle.AsRef<bool>(_PausedViaInputOffset.Value);
  }
  private static readonly Lazy<nint> _PauseAtNextInterruptOffset = new(() => Schema.GetOffset(0x1099B7017110D1BC), LazyThreadSafetyMode.None);

  public ref bool PauseAtNextInterrupt {
    get => ref _Handle.AsRef<bool>(_PauseAtNextInterruptOffset.Value);
  }
  private static readonly Lazy<nint> _WaitingForActorOffset = new(() => Schema.GetOffset(0x1099B701A8A67CC4), LazyThreadSafetyMode.None);

  public ref bool WaitingForActor {
    get => ref _Handle.AsRef<bool>(_WaitingForActorOffset.Value);
  }
  private static readonly Lazy<nint> _WaitingForInterruptOffset = new(() => Schema.GetOffset(0x1099B7015FF93F72), LazyThreadSafetyMode.None);

  public ref bool WaitingForInterrupt {
    get => ref _Handle.AsRef<bool>(_WaitingForInterruptOffset.Value);
  }
  private static readonly Lazy<nint> _InterruptedActorsScenesOffset = new(() => Schema.GetOffset(0x1099B7016CE93DF2), LazyThreadSafetyMode.None);

  public ref bool InterruptedActorsScenes {
    get => ref _Handle.AsRef<bool>(_InterruptedActorsScenesOffset.Value);
  }
  private static readonly Lazy<nint> _BreakOnNonIdleOffset = new(() => Schema.GetOffset(0x1099B7012DF0ACFA), LazyThreadSafetyMode.None);

  public ref bool BreakOnNonIdle {
    get => ref _Handle.AsRef<bool>(_BreakOnNonIdleOffset.Value);
  }
  private static readonly Lazy<nint> _SceneFinishedOffset = new(() => Schema.GetOffset(0x1099B701B78EE50D), LazyThreadSafetyMode.None);

  public ref bool SceneFinished {
    get => ref _Handle.AsRef<bool>(_SceneFinishedOffset.Value);
  }
  private static readonly Lazy<nint> _ActorListOffset = new(() => Schema.GetOffset(0x1099B701ABF34ACC), LazyThreadSafetyMode.None);

  public ref CUtlVector<CHandle<CBaseFlex>> ActorList {
    get => ref _Handle.AsRef<CUtlVector<CHandle<CBaseFlex>>>(_ActorListOffset.Value);
  }
  private static readonly Lazy<nint> _RemoveActorListOffset = new(() => Schema.GetOffset(0x1099B701C08C1458), LazyThreadSafetyMode.None);

  public ref CUtlVector<CHandle<CBaseEntity>> RemoveActorList {
    get => ref _Handle.AsRef<CUtlVector<CHandle<CBaseEntity>>>(_RemoveActorListOffset.Value);
  }
  private static readonly Lazy<nint> _SceneFlushCounterOffset = new(() => Schema.GetOffset(0x1099B701E744BD85), LazyThreadSafetyMode.None);

  public ref int SceneFlushCounter {
    get => ref _Handle.AsRef<int>(_SceneFlushCounterOffset.Value);
  }
  private static readonly Lazy<nint> _SceneStringIndexOffset = new(() => Schema.GetOffset(0x1099B7014B743F7E), LazyThreadSafetyMode.None);

  public ref ushort SceneStringIndex {
    get => ref _Handle.AsRef<ushort>(_SceneStringIndexOffset.Value);
  }
  private static readonly Lazy<nint> _OnStartOffset = new(() => Schema.GetOffset(0x1099B701C3FE848C), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnStart {
    get => new CEntityIOOutputImpl(_Handle + _OnStartOffset.Value);
  }
  private static readonly Lazy<nint> _OnCompletionOffset = new(() => Schema.GetOffset(0x1099B7010EADA43E), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnCompletion {
    get => new CEntityIOOutputImpl(_Handle + _OnCompletionOffset.Value);
  }
  private static readonly Lazy<nint> _OnCanceledOffset = new(() => Schema.GetOffset(0x1099B701F02162DB), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnCanceled {
    get => new CEntityIOOutputImpl(_Handle + _OnCanceledOffset.Value);
  }
  private static readonly Lazy<nint> _OnPausedOffset = new(() => Schema.GetOffset(0x1099B70191D78012), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnPaused {
    get => new CEntityIOOutputImpl(_Handle + _OnPausedOffset.Value);
  }
  private static readonly Lazy<nint> _OnResumedOffset = new(() => Schema.GetOffset(0x1099B701CCA87325), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnResumed {
    get => new CEntityIOOutputImpl(_Handle + _OnResumedOffset.Value);
  }
  private static readonly Lazy<nint> _OnTriggerOffset = new(() => Schema.GetOffset(0x1099B70181E0BFEC), LazyThreadSafetyMode.None);

  public SchemaUntypedField OnTrigger {
    get => new SchemaUntypedField(_Handle + _OnTriggerOffset.Value);
  }
  private static readonly Lazy<nint> _InterruptSceneOffset = new(() => Schema.GetOffset(0x1099B7019B121B62), LazyThreadSafetyMode.None);

  public ref CHandle<CSceneEntity> InterruptScene {
    get => ref _Handle.AsRef<CHandle<CSceneEntity>>(_InterruptSceneOffset.Value);
  }
  private static readonly Lazy<nint> _InterruptCountOffset = new(() => Schema.GetOffset(0x1099B70114AAD933), LazyThreadSafetyMode.None);

  public ref int InterruptCount {
    get => ref _Handle.AsRef<int>(_InterruptCountOffset.Value);
  }
  private static readonly Lazy<nint> _SceneMissingOffset = new(() => Schema.GetOffset(0x1099B7018E7EBF31), LazyThreadSafetyMode.None);

  public ref bool SceneMissing {
    get => ref _Handle.AsRef<bool>(_SceneMissingOffset.Value);
  }
  private static readonly Lazy<nint> _InterruptedOffset = new(() => Schema.GetOffset(0x1099B701ECF7A431), LazyThreadSafetyMode.None);

  public ref bool Interrupted {
    get => ref _Handle.AsRef<bool>(_InterruptedOffset.Value);
  }
  private static readonly Lazy<nint> _CompletedEarlyOffset = new(() => Schema.GetOffset(0x1099B701DDF4B191), LazyThreadSafetyMode.None);

  public ref bool CompletedEarly {
    get => ref _Handle.AsRef<bool>(_CompletedEarlyOffset.Value);
  }
  private static readonly Lazy<nint> _InterruptSceneFinishedOffset = new(() => Schema.GetOffset(0x1099B701FA6A4266), LazyThreadSafetyMode.None);

  public ref bool InterruptSceneFinished {
    get => ref _Handle.AsRef<bool>(_InterruptSceneFinishedOffset.Value);
  }
  private static readonly Lazy<nint> _RestoringOffset = new(() => Schema.GetOffset(0x1099B70103F03702), LazyThreadSafetyMode.None);

  public ref bool Restoring {
    get => ref _Handle.AsRef<bool>(_RestoringOffset.Value);
  }
  private static readonly Lazy<nint> _NotifySceneCompletionOffset = new(() => Schema.GetOffset(0x1099B70111F17358), LazyThreadSafetyMode.None);

  public ref CUtlVector<CHandle<CSceneEntity>> NotifySceneCompletion {
    get => ref _Handle.AsRef<CUtlVector<CHandle<CSceneEntity>>>(_NotifySceneCompletionOffset.Value);
  }
  private static readonly Lazy<nint> _ListManagersOffset = new(() => Schema.GetOffset(0x1099B701AD7882DF), LazyThreadSafetyMode.None);

  public ref CUtlVector<CHandle<CSceneListManager>> ListManagers {
    get => ref _Handle.AsRef<CUtlVector<CHandle<CSceneListManager>>>(_ListManagersOffset.Value);
  }
  private static readonly Lazy<nint> _SoundNameOffset = new(() => Schema.GetOffset(0x1099B701B17EB157), LazyThreadSafetyMode.None);

  public string SoundName {
    get {
      var ptr = _Handle.Read<nint>(_SoundNameOffset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _SoundNameOffset.Value, value);
  } 
  private static readonly Lazy<nint> _SequenceNameOffset = new(() => Schema.GetOffset(0x1099B701A55BC593), LazyThreadSafetyMode.None);

  public string SequenceName {
    get {
      var ptr = _Handle.Read<nint>(_SequenceNameOffset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _SequenceNameOffset.Value, value);
  } 
  private static readonly Lazy<nint> _ActorOffset = new(() => Schema.GetOffset(0x1099B701C0FFC404), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseFlex> Actor {
    get => ref _Handle.AsRef<CHandle<CBaseFlex>>(_ActorOffset.Value);
  }
  private static readonly Lazy<nint> _ActivatorOffset = new(() => Schema.GetOffset(0x1099B701AB093BB2), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> Activator {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_ActivatorOffset.Value);
  }
  private static readonly Lazy<nint> _BusyActorOffset = new(() => Schema.GetOffset(0x1099B70124F0E411), LazyThreadSafetyMode.None);

  public ref int BusyActor {
    get => ref _Handle.AsRef<int>(_BusyActorOffset.Value);
  }
  private static readonly Lazy<nint> _PlayerDeathBehaviorOffset = new(() => Schema.GetOffset(0x1099B701C6ECC93B), LazyThreadSafetyMode.None);

  public ref SceneOnPlayerDeath_t PlayerDeathBehavior {
    get => ref _Handle.AsRef<SceneOnPlayerDeath_t>(_PlayerDeathBehaviorOffset.Value);
  }

  public void IsPlayingBackUpdated() {
    Schema.Update(_Handle, 0x1099B70133D9EB62);
  }
  public void PausedUpdated() {
    Schema.Update(_Handle, 0x1099B7016E4C592B);
  }
  public void MultiplayerUpdated() {
    Schema.Update(_Handle, 0x1099B70140E33A8B);
  }
  public void AutogeneratedUpdated() {
    Schema.Update(_Handle, 0x1099B701CD800D57);
  }
  public void ForceClientTimeUpdated() {
    Schema.Update(_Handle, 0x1099B7010AE43350);
  }
  public void ActorListUpdated() {
    Schema.Update(_Handle, 0x1099B701ABF34ACC);
  }
  public void SceneStringIndexUpdated() {
    Schema.Update(_Handle, 0x1099B7014B743F7E);
  }
}