// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSoundEventOBBEntityImpl : CSoundEventEntityImpl, CSoundEventOBBEntity
{
    public CSoundEventOBBEntityImpl(nint handle) : base(handle) { }

    private static nint? _MinsOffset;

    public ref Vector Mins {
        get {
            _MinsOffset = _MinsOffset ?? Schema.GetOffset(0x470330BB421BB730);
            return ref _Handle.AsRef<Vector>(_MinsOffset!.Value);
        }
    }
    private static nint? _MaxsOffset;

    public ref Vector Maxs {
        get {
            _MaxsOffset = _MaxsOffset ?? Schema.GetOffset(0x470330BBC0C1CE6A);
            return ref _Handle.AsRef<Vector>(_MaxsOffset!.Value);
        }
    }

    public void MinsUpdated() => Schema.Update(_Handle, 0x470330BB421BB730);
    public void MaxsUpdated() => Schema.Update(_Handle, 0x470330BBC0C1CE6A);
}