// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSoundEventParameterImpl : CBaseEntityImpl, CSoundEventParameter {

  public CSoundEventParameterImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _ParamNameOffset = new(() => Schema.GetOffset(0xEFEED49AFF6F4311), LazyThreadSafetyMode.None);

  public string ParamName {
    get {
      var ptr = _Handle.Read<nint>(_ParamNameOffset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _ParamNameOffset.Value, value);
  } 
  private static readonly Lazy<nint> _FloatValueOffset = new(() => Schema.GetOffset(0xEFEED49A80BDA558), LazyThreadSafetyMode.None);

  public ref float FloatValue {
    get => ref _Handle.AsRef<float>(_FloatValueOffset.Value);
  }


}