// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSoundAreaEntityBaseImpl : CBaseEntityImpl, CSoundAreaEntityBase {

  public CSoundAreaEntityBaseImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _DisabledOffset = new(() => Schema.GetOffset(0x15C90E163A7C5965), LazyThreadSafetyMode.None);

  public ref bool Disabled {
    get => ref _Handle.AsRef<bool>(_DisabledOffset.Value);
  }
  private static readonly Lazy<nint> _SoundAreaTypeOffset = new(() => Schema.GetOffset(0x15C90E16227612E5), LazyThreadSafetyMode.None);

  public string SoundAreaType {
    get {
      var ptr = _Handle.Read<nint>(_SoundAreaTypeOffset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _SoundAreaTypeOffset.Value, value);
  } 
  private static readonly Lazy<nint> _PosOffset = new(() => Schema.GetOffset(0x15C90E16DE9CFC5D), LazyThreadSafetyMode.None);

  public ref Vector Pos {
    get => ref _Handle.AsRef<Vector>(_PosOffset.Value);
  }

  public void DisabledUpdated() {
    Schema.Update(_Handle, 0x15C90E163A7C5965);
  }
  public void SoundAreaTypeUpdated() {
    Schema.Update(_Handle, 0x15C90E16227612E5);
  }
  public void PosUpdated() {
    Schema.Update(_Handle, 0x15C90E16DE9CFC5D);
  }
}