// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CStepsRemainingMetricEvaluatorImpl : CMotionMetricEvaluatorImpl, CStepsRemainingMetricEvaluator
{
    public CStepsRemainingMetricEvaluatorImpl(nint handle) : base(handle) { }

    private static nint? _FootIndicesOffset;

    public ref CUtlVector<int> FootIndices {
        get {
            _FootIndicesOffset = _FootIndicesOffset ?? Schema.GetOffset(0xDDD8E3884C840316);
            return ref _Handle.AsRef<CUtlVector<int>>(_FootIndicesOffset!.Value);
        }
    }
    private static nint? _MinStepsRemainingOffset;

    public ref float MinStepsRemaining {
        get {
            _MinStepsRemainingOffset = _MinStepsRemainingOffset ?? Schema.GetOffset(0xDDD8E388382CE1FC);
            return ref _Handle.AsRef<float>(_MinStepsRemainingOffset!.Value);
        }
    }


}