// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTestPulseIOImpl : CLogicalEntityImpl, CTestPulseIO {

  public CTestPulseIOImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _OnVariantVoidOffset = new(() => Schema.GetOffset(0x3CAD66134B0C5D73), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnVariantVoid {
    get => new CEntityIOOutputImpl(_Handle + _OnVariantVoidOffset.Value);
  }
  private static readonly Lazy<nint> _OnVariantBoolOffset = new(() => Schema.GetOffset(0x3CAD66138350E481), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnVariantBool {
    get => new CEntityIOOutputImpl(_Handle + _OnVariantBoolOffset.Value);
  }
  private static readonly Lazy<nint> _OnVariantIntOffset = new(() => Schema.GetOffset(0x3CAD66131C6BA682), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnVariantInt {
    get => new CEntityIOOutputImpl(_Handle + _OnVariantIntOffset.Value);
  }
  private static readonly Lazy<nint> _OnVariantFloatOffset = new(() => Schema.GetOffset(0x3CAD661378E46379), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnVariantFloat {
    get => new CEntityIOOutputImpl(_Handle + _OnVariantFloatOffset.Value);
  }
  private static readonly Lazy<nint> _OnVariantStringOffset = new(() => Schema.GetOffset(0x3CAD6613DE2E3E5C), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnVariantString {
    get => new CEntityIOOutputImpl(_Handle + _OnVariantStringOffset.Value);
  }
  private static readonly Lazy<nint> _OnVariantColorOffset = new(() => Schema.GetOffset(0x3CAD66139A1362C4), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnVariantColor {
    get => new CEntityIOOutputImpl(_Handle + _OnVariantColorOffset.Value);
  }
  private static readonly Lazy<nint> _OnVariantVectorOffset = new(() => Schema.GetOffset(0x3CAD6613A6D8BE1E), LazyThreadSafetyMode.None);

  public CEntityIOOutput OnVariantVector {
    get => new CEntityIOOutputImpl(_Handle + _OnVariantVectorOffset.Value);
  }
  private static readonly Lazy<nint> _AllowEmptyInputsOffset = new(() => Schema.GetOffset(0x3CAD661342A93BD2), LazyThreadSafetyMode.None);

  public ref bool AllowEmptyInputs {
    get => ref _Handle.AsRef<bool>(_AllowEmptyInputsOffset.Value);
  }


}