// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTriggerProximityImpl : CBaseTriggerImpl, CTriggerProximity {

  public CTriggerProximityImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _MeasureTargetOffset = new(() => Schema.GetOffset(0x98F0621FF81BC1A8), LazyThreadSafetyMode.None);

  public ref CHandle<CBaseEntity> MeasureTarget {
    get => ref _Handle.AsRef<CHandle<CBaseEntity>>(_MeasureTargetOffset.Value);
  }
  private static readonly Lazy<nint> _MeasureTarget1Offset = new(() => Schema.GetOffset(0x98F0621F29C47B3A), LazyThreadSafetyMode.None);

  public string MeasureTarget1 {
    get {
      var ptr = _Handle.Read<nint>(_MeasureTarget1Offset.Value);
      return Schema.GetString(ptr);
    }
    set => Schema.SetString(_Handle, _MeasureTarget1Offset.Value, value);
  } 
  private static readonly Lazy<nint> _RadiusOffset = new(() => Schema.GetOffset(0x98F0621F2E1F6E07), LazyThreadSafetyMode.None);

  public ref float Radius {
    get => ref _Handle.AsRef<float>(_RadiusOffset.Value);
  }
  private static readonly Lazy<nint> _TouchersOffset = new(() => Schema.GetOffset(0x98F0621FA0F3A2B0), LazyThreadSafetyMode.None);

  public ref int Touchers {
    get => ref _Handle.AsRef<int>(_TouchersOffset.Value);
  }
  private static readonly Lazy<nint> _NearestEntityDistanceOffset = new(() => Schema.GetOffset(0x98F0621F28AD73D5), LazyThreadSafetyMode.None);

  public SchemaUntypedField NearestEntityDistance {
    get => new SchemaUntypedField(_Handle + _NearestEntityDistanceOffset.Value);
  }


}