// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVoiceContainerAmpedDecayingSineWaveImpl : CVoiceContainerDecayingSineWaveImpl, CVoiceContainerAmpedDecayingSineWave {

  public CVoiceContainerAmpedDecayingSineWaveImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _GainAmountOffset = new(() => Schema.GetOffset(0x312CFD9CB3BC88F4), LazyThreadSafetyMode.None);

  public ref float GainAmount {
    get => ref _Handle.AsRef<float>(_GainAmountOffset.Value);
  }


}