// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class DynamicVolumeDef_tImpl : SchemaClass, DynamicVolumeDef_t
{
    public DynamicVolumeDef_tImpl(nint handle) : base(handle) { }

    private static nint? _SourceOffset;

    public ref CHandle<CBaseEntity> Source {
        get {
            _SourceOffset = _SourceOffset ?? Schema.GetOffset(0x9D661554D0835C78);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_SourceOffset!.Value);
        }
    }
    private static nint? _TargetOffset;

    public ref CHandle<CBaseEntity> Target {
        get {
            _TargetOffset = _TargetOffset ?? Schema.GetOffset(0x9D661554FA08A9E8);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_TargetOffset!.Value);
        }
    }
    private static nint? _HullIdxOffset;

    public ref int HullIdx {
        get {
            _HullIdxOffset = _HullIdxOffset ?? Schema.GetOffset(0x9D661554595B303D);
            return ref _Handle.AsRef<int>(_HullIdxOffset!.Value);
        }
    }
    private static nint? _SourceAnchorPosOffset;

    public ref Vector SourceAnchorPos {
        get {
            _SourceAnchorPosOffset = _SourceAnchorPosOffset ?? Schema.GetOffset(0x9D661554E6AC3899);
            return ref _Handle.AsRef<Vector>(_SourceAnchorPosOffset!.Value);
        }
    }
    private static nint? _TargetAnchorPosOffset;

    public ref Vector TargetAnchorPos {
        get {
            _TargetAnchorPosOffset = _TargetAnchorPosOffset ?? Schema.GetOffset(0x9D6615540976AD91);
            return ref _Handle.AsRef<Vector>(_TargetAnchorPosOffset!.Value);
        }
    }
    private static nint? _AreaSrcOffset;

    public ref uint AreaSrc {
        get {
            _AreaSrcOffset = _AreaSrcOffset ?? Schema.GetOffset(0x9D661554E55D859E);
            return ref _Handle.AsRef<uint>(_AreaSrcOffset!.Value);
        }
    }
    private static nint? _AreaDstOffset;

    public ref uint AreaDst {
        get {
            _AreaDstOffset = _AreaDstOffset ?? Schema.GetOffset(0x9D66155487799313);
            return ref _Handle.AsRef<uint>(_AreaDstOffset!.Value);
        }
    }
    private static nint? _AttachedOffset;

    public ref bool Attached {
        get {
            _AttachedOffset = _AttachedOffset ?? Schema.GetOffset(0x9D6615544C8B6515);
            return ref _Handle.AsRef<bool>(_AttachedOffset!.Value);
        }
    }


}