// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class EngineLoopState_tImpl : SchemaClass, EngineLoopState_t {

  public EngineLoopState_tImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _PlatWindowWidthOffset = new(() => Schema.GetOffset(0x8A7EC4513AF18278), LazyThreadSafetyMode.None);

  public ref int PlatWindowWidth {
    get => ref _Handle.AsRef<int>(_PlatWindowWidthOffset.Value);
  }
  private static readonly Lazy<nint> _PlatWindowHeightOffset = new(() => Schema.GetOffset(0x8A7EC45157A7B88F), LazyThreadSafetyMode.None);

  public ref int PlatWindowHeight {
    get => ref _Handle.AsRef<int>(_PlatWindowHeightOffset.Value);
  }
  private static readonly Lazy<nint> _RenderWidthOffset = new(() => Schema.GetOffset(0x8A7EC45179B0DC63), LazyThreadSafetyMode.None);

  public ref int RenderWidth {
    get => ref _Handle.AsRef<int>(_RenderWidthOffset.Value);
  }
  private static readonly Lazy<nint> _RenderHeightOffset = new(() => Schema.GetOffset(0x8A7EC451A184E51E), LazyThreadSafetyMode.None);

  public ref int RenderHeight {
    get => ref _Handle.AsRef<int>(_RenderHeightOffset.Value);
  }


}