// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FeDynKinLink_tImpl : SchemaClass, FeDynKinLink_t
{
    public FeDynKinLink_tImpl(nint handle) : base(handle) { }

    private static nint? _ParentOffset;

    public ref ushort Parent {
        get {
            _ParentOffset = _ParentOffset ?? Schema.GetOffset(0xA0FBF6C40AABB9D1);
            return ref _Handle.AsRef<ushort>(_ParentOffset!.Value);
        }
    }
    private static nint? _ChildOffset;

    public ref ushort Child {
        get {
            _ChildOffset = _ChildOffset ?? Schema.GetOffset(0xA0FBF6C4FE653481);
            return ref _Handle.AsRef<ushort>(_ChildOffset!.Value);
        }
    }


}