// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class FeTaperedCapsuleRigid_tImpl : SchemaClass, FeTaperedCapsuleRigid_t {

  public FeTaperedCapsuleRigid_tImpl(nint handle) : base(handle) {
  }

  public ISchemaFixedArray<fltx4> Sphere {
    get => new SchemaFixedArray<fltx4>(_Handle, 0x4B2017EE9E2AC48C, 2, 16, 16);
  }
  private static readonly Lazy<nint> _NodeOffset = new(() => Schema.GetOffset(0x4B2017EECD6694B9), LazyThreadSafetyMode.None);

  public ref ushort Node {
    get => ref _Handle.AsRef<ushort>(_NodeOffset.Value);
  }
  private static readonly Lazy<nint> _CollisionMaskOffset = new(() => Schema.GetOffset(0x4B2017EE0ED3454F), LazyThreadSafetyMode.None);

  public ref ushort CollisionMask {
    get => ref _Handle.AsRef<ushort>(_CollisionMaskOffset.Value);
  }
  private static readonly Lazy<nint> _VertexMapIndexOffset = new(() => Schema.GetOffset(0x4B2017EE7B332E39), LazyThreadSafetyMode.None);

  public ref ushort VertexMapIndex {
    get => ref _Handle.AsRef<ushort>(_VertexMapIndexOffset.Value);
  }
  private static readonly Lazy<nint> _FlagsOffset = new(() => Schema.GetOffset(0x4B2017EEB8D52E48), LazyThreadSafetyMode.None);

  public ref ushort Flags {
    get => ref _Handle.AsRef<ushort>(_FlagsOffset.Value);
  }


}