// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ModelBoneFlexDriver_tImpl : SchemaClass, ModelBoneFlexDriver_t
{
    public ModelBoneFlexDriver_tImpl(nint handle) : base(handle) { }

    private static nint? _BoneNameOffset;

    public string BoneName {
        get {
            _BoneNameOffset = _BoneNameOffset ?? Schema.GetOffset(0xBCBDE5AAFDEE0E0C);
            return Schema.GetString(_Handle.Read<nint>(_BoneNameOffset!.Value));
        }
        set {
            _BoneNameOffset = _BoneNameOffset ?? Schema.GetOffset(0xBCBDE5AAFDEE0E0C);
            Schema.SetString(_Handle, _BoneNameOffset!.Value, value);
        }
    } 
    private static nint? _BoneNameTokenOffset;

    public ref uint BoneNameToken {
        get {
            _BoneNameTokenOffset = _BoneNameTokenOffset ?? Schema.GetOffset(0xBCBDE5AA44D1E369);
            return ref _Handle.AsRef<uint>(_BoneNameTokenOffset!.Value);
        }
    }
    private static nint? _ControlsOffset;

    public ref CUtlVector<ModelBoneFlexDriverControl_t> Controls {
        get {
            _ControlsOffset = _ControlsOffset ?? Schema.GetOffset(0xBCBDE5AA5FCAD2B7);
            return ref _Handle.AsRef<CUtlVector<ModelBoneFlexDriverControl_t>>(_ControlsOffset!.Value);
        }
    }


}