// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ParamSpanSample_tImpl : SchemaClass, ParamSpanSample_t
{
    public ParamSpanSample_tImpl(nint handle) : base(handle) { }

    private static nint? _ValueOffset;

    public SchemaUntypedField Value {
        get {
            _ValueOffset = _ValueOffset ?? Schema.GetOffset(0x37E203136B99AEEA);
            return new SchemaUntypedField(_Handle + _ValueOffset!.Value);
        }
    }
    private static nint? _CycleOffset;

    public ref float Cycle {
        get {
            _CycleOffset = _CycleOffset ?? Schema.GetOffset(0x37E203130C77829F);
            return ref _Handle.AsRef<float>(_CycleOffset!.Value);
        }
    }


}