// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ResourceId_tImpl : SchemaClass, ResourceId_t
{
    public ResourceId_tImpl(nint handle) : base(handle) { }

    private static nint? _ValueOffset;

    public ref ulong Value {
        get {
            _ValueOffset = _ValueOffset ?? Schema.GetOffset(0x21F7998BDCB0894A);
            return ref _Handle.AsRef<ulong>(_ValueOffset!.Value);
        }
    }


}