// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.SchemaDefinitions;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ResponseParamsImpl : SchemaClass, ResponseParams {

  public ResponseParamsImpl(nint handle) : base(handle) {
  }

  private static readonly Lazy<nint> _OddsOffset = new(() => Schema.GetOffset(0x5C5BE8C4E9B76DD7), LazyThreadSafetyMode.None);

  public ref short Odds {
    get => ref _Handle.AsRef<short>(_OddsOffset.Value);
  }
  private static readonly Lazy<nint> _FlagsOffset = new(() => Schema.GetOffset(0x5C5BE8C49C677A2C), LazyThreadSafetyMode.None);

  public ref short Flags {
    get => ref _Handle.AsRef<short>(_FlagsOffset.Value);
  }
  private static readonly Lazy<nint> _FollowupOffset = new(() => Schema.GetOffset(0x5C5BE8C481D8C38F), LazyThreadSafetyMode.None);

  public ResponseFollowup? Followup {
    get {
      var ptr = _Handle.Read<nint>(_FollowupOffset.Value);
      return ptr.IsValidPtr() ? new ResponseFollowupImpl(ptr) : null;
    }
  }


}