// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class RnMeshDesc_tImpl : RnShapeDesc_tImpl, RnMeshDesc_t
{
    public RnMeshDesc_tImpl(nint handle) : base(handle) { }

    private static nint? _MeshOffset;

    public RnMesh_t Mesh {
        get {
            _MeshOffset = _MeshOffset ?? Schema.GetOffset(0xB236F002DEAFA33C);
            return new RnMesh_tImpl(_Handle + _MeshOffset!.Value);
        }
    }


}